// <auto-generated />
using AppRisks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppRisks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221118122252_AddSummaryToRiskExpertMarkCategory")]
    partial class AddSummaryToRiskExpertMarkCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskCategoryId");

                    b.ToTable("Risks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Функціональні характеристики ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Характеристики якості ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Характеристики надійності ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Застосовність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Часова продуктивність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Супроводжуваність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Повторне використання компонент ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Обмеження сумарного бюджету на програмний продукт",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Недоступна вартість реалізації програмного проекту",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Низька ступінь реалізму при оцінюванні витрат на програмний проект",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "Властивості та можливості гнучкості внесення змін до планів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            Content = "Можливості порушення встановлених термінів реалізації етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            Content = "Низька ступінь реалізму при встановленні планів і етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Хибна стратегія реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "Неефективне планування проекту розроблення ПЗ",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Неякісне оцінювання програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 17,
                            Content = "Прогалини в документуванні етапів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 18,
                            Content = "Промахи в прогнозуванні результатів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 19,
                            Content = "Затримки у постачанні обладнання, необхідного для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "Затримки у постачанні інструментальних засобів, необхідних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Небажання команди виконавців використовувати інструментальні засоби для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Content = "Формування запитів на більш потужні інструментальні засоби розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "Відмова команди виконавців від CASE-засобів розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 24,
                            Content = "Неефективність програмного коду, згенерованого CASE-засобами розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 25,
                            Content = "Неможливість інтеграції CASE-засобів з іншими інструментальними засобами для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "Недостатня продуктивність баз(и) даних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 27,
                            Content = "Програмні компоненти, які використовують повторно в ПЗ, мають дефекти та обмежені функціональні можливості",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "Швидкість виявлення дефектів у програмному коді є нижчою від раніше запланованих термінів",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 29,
                            Content = "Поява дефектних системних компонент, які використовують для розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Content = "Недо(пере)оцінювання витрат на реалізацію програмного проекту (надмірно низька вартість)",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 31,
                            Content = "Фінансові ускладнення у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 32,
                            Content = "Фінансові ускладнення у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 33,
                            Content = "Змен(збіль)шення бюджету програмного проекта з ініціативи компанії-замовника ПЗ під час його реалізації",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            Content = "Висока вартість виконання повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 35,
                            Content = "Реорганізація структурних підрозділів у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 36,
                            Content = "Реорганізація команди виконавців у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 37,
                            Content = "Зміни графіка виконання робіт з боку замовника чи розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            Content = "Порушення графіка виконання робіт з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 39,
                            Content = "Потреба зміни користувацьких вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 40,
                            Content = "Потреба зміни функціональних вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 41,
                            Content = "Потреба виконання великої кількості повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 42,
                            Content = "Недо(пере)оцінювання тривалості етапів реалізації програмного проекту з боку компанії-замовника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 43,
                            Content = "Остаточний розмір ПЗ значно перевищує (менший від) заплановані(их) його характеристики",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 44,
                            Content = "Поява на ринку аналогічного ПЗ до виходу замовленого",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 45,
                            Content = "Поява на ринку більш конкурентоздатного ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 46,
                            Content = "Низький моральний стан персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 47,
                            Content = "Низька взаємодія між членами команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 48,
                            Content = "Пасивність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 49,
                            Content = "Недостатня компетентність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 50,
                            Content = "Незадоволеність замовника результатами етапів реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 51,
                            Content = "Недостатня кількість фахівців у команді виконавців ПЗ з необхідним професійним рівнем",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 52,
                            Content = "Хвороба провідного виконавця в найкритичніший момент розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 53,
                            Content = "Одночасна хвороба декількох виконавців підчас розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 54,
                            Content = "Неможливість організації необхідного навчання персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 55,
                            Content = "Зміна пріоритетів у процесі управління програмним проектом",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "Недо(пере)оцінювання необхідної кількості розробників (підрядників і субпідрядників) на етапах життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 57,
                            Content = "Недостатнє (надмірне) документування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 58,
                            Content = "Нереалістичне прогнозування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 59,
                            Content = "Недостатній професійний рівень представників від компанії-замовника ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Множина джерел появи технічних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Множина джерел появи вартісних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Множина джерел появи планових ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Множина джерел появи ризиків реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Множина настання технічних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Множина настання вартісних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Множина настання планових ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ExpertMark1")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark10")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark2")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark3")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark4")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark5")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark6")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark7")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark8")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark9")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RiskExpertMarksCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.Property<double>("Summary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RiskExpertMarksCategoryId");

                    b.HasIndex("RiskId");

                    b.ToTable("RiskExpertMarksEnumerable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertMark1 = 0.58498322927366675,
                            ExpertMark10 = 0.17098971629967596,
                            ExpertMark2 = 0.3966129548492997,
                            ExpertMark3 = 0.49190184873368303,
                            ExpertMark4 = 0.79404969134118686,
                            ExpertMark5 = 0.33723320942018109,
                            ExpertMark6 = 0.53337138730832334,
                            ExpertMark7 = 0.0089359019509619442,
                            ExpertMark8 = 0.13140224738473316,
                            ExpertMark9 = 0.67113654549977331,
                            Price = 43.563762961287352,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 19,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 2,
                            ExpertMark1 = 0.82842223145432359,
                            ExpertMark10 = 0.82179840865941989,
                            ExpertMark2 = 0.42648748437279904,
                            ExpertMark3 = 0.72305523854481624,
                            ExpertMark4 = 0.49755796879659531,
                            ExpertMark5 = 0.21864917611156087,
                            ExpertMark6 = 0.49428470781138734,
                            ExpertMark7 = 0.49567723400644781,
                            ExpertMark8 = 0.6851494989840069,
                            ExpertMark9 = 0.49004512005025869,
                            Price = 37.836752496622786,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 20,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 3,
                            ExpertMark1 = 0.44765378831718616,
                            ExpertMark10 = 0.44890569114759526,
                            ExpertMark2 = 0.61999448697031256,
                            ExpertMark3 = 0.048040480073383129,
                            ExpertMark4 = 0.59540377980361492,
                            ExpertMark5 = 0.9588796227770473,
                            ExpertMark6 = 0.7576585075865595,
                            ExpertMark7 = 0.92219156592111062,
                            ExpertMark8 = 0.31678804744826705,
                            ExpertMark9 = 0.19800028608824316,
                            Price = 75.059635709234684,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 21,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 4,
                            ExpertMark1 = 0.68669959355047128,
                            ExpertMark10 = 0.90677889072543783,
                            ExpertMark2 = 0.85488665652158224,
                            ExpertMark3 = 0.024867115028991971,
                            ExpertMark4 = 0.39688647316834669,
                            ExpertMark5 = 0.47021344981649871,
                            ExpertMark6 = 0.65437293273133157,
                            ExpertMark7 = 0.71464849590641488,
                            ExpertMark8 = 0.11813811564997245,
                            ExpertMark9 = 0.48876562588273798,
                            Price = 18.766273337095406,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 22,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 5,
                            ExpertMark1 = 0.89143595272745435,
                            ExpertMark10 = 0.63251093571243944,
                            ExpertMark2 = 0.40501573320733231,
                            ExpertMark3 = 0.89318289104003767,
                            ExpertMark4 = 0.60291480089612548,
                            ExpertMark5 = 0.10379798316023836,
                            ExpertMark6 = 0.56160778766417252,
                            ExpertMark7 = 0.30674898256930849,
                            ExpertMark8 = 0.59909669612553451,
                            ExpertMark9 = 0.83394277740506606,
                            Price = 3.9773320475636087,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 23,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 6,
                            ExpertMark1 = 0.52756219483614808,
                            ExpertMark10 = 0.98977011199211284,
                            ExpertMark2 = 0.41246421913792175,
                            ExpertMark3 = 0.68783171511367536,
                            ExpertMark4 = 0.18582837095341953,
                            ExpertMark5 = 0.65942768732670287,
                            ExpertMark6 = 0.099069565764842271,
                            ExpertMark7 = 0.60398223926223527,
                            ExpertMark8 = 0.089050458252833975,
                            ExpertMark9 = 0.73461244276986526,
                            Price = 51.96433090648145,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 24,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 7,
                            ExpertMark1 = 0.11307285059554639,
                            ExpertMark10 = 0.12421975298724819,
                            ExpertMark2 = 0.39536144111932114,
                            ExpertMark3 = 0.82449654018719232,
                            ExpertMark4 = 0.90264398218702624,
                            ExpertMark5 = 0.55574678591657045,
                            ExpertMark6 = 0.10816055133512625,
                            ExpertMark7 = 0.49821303244006609,
                            ExpertMark8 = 0.62675285669475378,
                            ExpertMark9 = 0.53763637773617345,
                            Price = 92.447467887803725,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 25,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 8,
                            ExpertMark1 = 0.83678068644193171,
                            ExpertMark10 = 0.073949932885167824,
                            ExpertMark2 = 0.012879797583455588,
                            ExpertMark3 = 0.82742827810530795,
                            ExpertMark4 = 0.83842885231875308,
                            ExpertMark5 = 0.56649525010721713,
                            ExpertMark6 = 0.93217997899356553,
                            ExpertMark7 = 0.073057345382414707,
                            ExpertMark8 = 0.66731118020974156,
                            ExpertMark9 = 0.26788911673393934,
                            Price = 94.142631548649121,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 26,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 9,
                            ExpertMark1 = 0.016454005376101533,
                            ExpertMark10 = 0.47429152019354115,
                            ExpertMark2 = 0.21247140062407832,
                            ExpertMark3 = 0.63955073207123425,
                            ExpertMark4 = 0.34817486457226476,
                            ExpertMark5 = 0.47127779626428346,
                            ExpertMark6 = 0.31264201120965684,
                            ExpertMark7 = 0.049871633378498648,
                            ExpertMark8 = 0.15161376401199289,
                            ExpertMark9 = 0.71447026452110962,
                            Price = 79.467952810736634,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 27,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 10,
                            ExpertMark1 = 0.76709087480302629,
                            ExpertMark10 = 0.059463293741008005,
                            ExpertMark2 = 0.78055544516520237,
                            ExpertMark3 = 0.88261371791323351,
                            ExpertMark4 = 0.85925828962833006,
                            ExpertMark5 = 0.11829932438734114,
                            ExpertMark6 = 0.17366865007126286,
                            ExpertMark7 = 0.66223255603470776,
                            ExpertMark8 = 0.70033164500138734,
                            ExpertMark9 = 0.49872233614278705,
                            Price = 40.389492726537647,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 28,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 11,
                            ExpertMark1 = 0.47490776457176809,
                            ExpertMark10 = 0.41139384145957281,
                            ExpertMark2 = 0.39570513420499809,
                            ExpertMark3 = 0.6488950453824488,
                            ExpertMark4 = 0.014353711048873175,
                            ExpertMark5 = 0.84238924018274597,
                            ExpertMark6 = 0.98962492021992654,
                            ExpertMark7 = 0.20527473812545471,
                            ExpertMark8 = 0.59140132938121404,
                            ExpertMark9 = 0.15639070671281441,
                            Price = 17.531949240436862,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 29,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 12,
                            ExpertMark1 = 0.71369316386375714,
                            ExpertMark10 = 0.84514815768427143,
                            ExpertMark2 = 0.88028407366333006,
                            ExpertMark3 = 0.82453962187257779,
                            ExpertMark4 = 0.0021238161757096696,
                            ExpertMark5 = 0.23066433552897636,
                            ExpertMark6 = 0.81525303943775351,
                            ExpertMark7 = 0.19537597612870161,
                            ExpertMark8 = 0.67992606021947499,
                            ExpertMark9 = 0.52876138516095972,
                            Price = 52.109064836264317,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 30,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 13,
                            ExpertMark1 = 0.75540889183979454,
                            ExpertMark10 = 0.82004791727829052,
                            ExpertMark2 = 0.037781098587834849,
                            ExpertMark3 = 0.31024901554665985,
                            ExpertMark4 = 0.47026538446885269,
                            ExpertMark5 = 0.13585702431789137,
                            ExpertMark6 = 0.60865312220768919,
                            ExpertMark7 = 0.68935352740874078,
                            ExpertMark8 = 0.80355716933801291,
                            ExpertMark9 = 0.18395767965992293,
                            Price = 15.714975876673808,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 31,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 14,
                            ExpertMark1 = 0.0064565339356668083,
                            ExpertMark10 = 0.7172359735667212,
                            ExpertMark2 = 0.48715188368294116,
                            ExpertMark3 = 0.75875970589524144,
                            ExpertMark4 = 0.31589921544120503,
                            ExpertMark5 = 0.8562024499810601,
                            ExpertMark6 = 0.61379279592500513,
                            ExpertMark7 = 0.54510570724265861,
                            ExpertMark8 = 0.48467749994748155,
                            ExpertMark9 = 0.25753132756598307,
                            Price = 72.366751878107138,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 32,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 15,
                            ExpertMark1 = 0.94271313081603769,
                            ExpertMark10 = 0.08530757595346683,
                            ExpertMark2 = 0.040212444093698063,
                            ExpertMark3 = 0.93122756547237795,
                            ExpertMark4 = 0.24853112495072982,
                            ExpertMark5 = 0.86000997673009849,
                            ExpertMark6 = 0.39662409541756827,
                            ExpertMark7 = 0.5724203944118581,
                            ExpertMark8 = 0.47105279503323405,
                            ExpertMark9 = 0.31500287924631609,
                            Price = 3.9477855952404717,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 33,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 16,
                            ExpertMark1 = 0.84054621413826269,
                            ExpertMark10 = 0.021270623687387857,
                            ExpertMark2 = 0.75098828706092235,
                            ExpertMark3 = 0.61548084680829618,
                            ExpertMark4 = 0.12919064973086536,
                            ExpertMark5 = 0.64210558669173867,
                            ExpertMark6 = 0.33772177065228737,
                            ExpertMark7 = 0.98242314624506821,
                            ExpertMark8 = 0.43793972349417609,
                            ExpertMark9 = 0.097230578218767127,
                            Price = 74.307924614916345,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 34,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 17,
                            ExpertMark1 = 0.16569620193564438,
                            ExpertMark10 = 0.5093456470266301,
                            ExpertMark2 = 0.69256422813422258,
                            ExpertMark3 = 0.72079462873059952,
                            ExpertMark4 = 0.4222583626958718,
                            ExpertMark5 = 0.42368258951931603,
                            ExpertMark6 = 0.56351184805317256,
                            ExpertMark7 = 0.25542340859171908,
                            ExpertMark8 = 0.23578857339659764,
                            ExpertMark9 = 0.41589731372585892,
                            Price = 86.685831933345298,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 35,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 18,
                            ExpertMark1 = 0.34161701862248095,
                            ExpertMark10 = 0.083778267858793387,
                            ExpertMark2 = 0.90690845048289381,
                            ExpertMark3 = 0.41954068665830047,
                            ExpertMark4 = 0.5109120154278981,
                            ExpertMark5 = 0.16728407083689278,
                            ExpertMark6 = 0.39256741585590826,
                            ExpertMark7 = 0.64816274732334189,
                            ExpertMark8 = 0.0026239713842303169,
                            ExpertMark9 = 0.066694147017657524,
                            Price = 42.699638956832821,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 36,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 19,
                            ExpertMark1 = 0.85946724463578938,
                            ExpertMark10 = 0.48432316577370726,
                            ExpertMark2 = 0.59130659350081738,
                            ExpertMark3 = 0.72412851313501747,
                            ExpertMark4 = 0.039018791256653085,
                            ExpertMark5 = 0.88405251005684493,
                            ExpertMark6 = 0.78083037158676227,
                            ExpertMark7 = 0.29890259006689013,
                            ExpertMark8 = 0.26167486713951915,
                            ExpertMark9 = 0.34527454908294564,
                            Price = 84.121423479486197,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 37,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 20,
                            ExpertMark1 = 0.46585688594558483,
                            ExpertMark10 = 0.96163344629583081,
                            ExpertMark2 = 0.77977969525255131,
                            ExpertMark3 = 0.99849334264251721,
                            ExpertMark4 = 0.46777673453571122,
                            ExpertMark5 = 0.892042132964741,
                            ExpertMark6 = 0.55088694209638955,
                            ExpertMark7 = 0.87397909407582342,
                            ExpertMark8 = 0.57134093868182911,
                            ExpertMark9 = 0.15170863573464977,
                            Price = 35.98745152126196,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 38,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 21,
                            ExpertMark1 = 0.68533247505227934,
                            ExpertMark10 = 0.54511492182322652,
                            ExpertMark2 = 0.96458676208955063,
                            ExpertMark3 = 0.89480549889052785,
                            ExpertMark4 = 0.54472851016705937,
                            ExpertMark5 = 0.83970540943515148,
                            ExpertMark6 = 0.3813498446850625,
                            ExpertMark7 = 0.047267178540681964,
                            ExpertMark8 = 0.89522218465023828,
                            ExpertMark9 = 0.76061290693171391,
                            Price = 42.027049771132454,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 39,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 22,
                            ExpertMark1 = 0.94757818721932907,
                            ExpertMark10 = 0.19446949840457772,
                            ExpertMark2 = 0.35724942796016501,
                            ExpertMark3 = 0.56503093389716685,
                            ExpertMark4 = 0.14516600624068354,
                            ExpertMark5 = 0.092368466462482202,
                            ExpertMark6 = 0.30560915582297465,
                            ExpertMark7 = 0.97102418565986959,
                            ExpertMark8 = 0.67081717012310327,
                            ExpertMark9 = 0.29007105510046105,
                            Price = 98.445329523509542,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 40,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 23,
                            ExpertMark1 = 0.31693999303430831,
                            ExpertMark10 = 0.36307520341971444,
                            ExpertMark2 = 0.11638120198129842,
                            ExpertMark3 = 0.028009435645721892,
                            ExpertMark4 = 0.18865172045273493,
                            ExpertMark5 = 0.73159617346916261,
                            ExpertMark6 = 0.025066625138326137,
                            ExpertMark7 = 0.55656271448518835,
                            ExpertMark8 = 0.95311646222953716,
                            ExpertMark9 = 0.25731532979114702,
                            Price = 12.042233917818645,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 41,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 24,
                            ExpertMark1 = 0.50829103473649173,
                            ExpertMark10 = 0.076579843841483419,
                            ExpertMark2 = 0.12621302161886805,
                            ExpertMark3 = 0.080392350575520632,
                            ExpertMark4 = 0.56161829027398524,
                            ExpertMark5 = 0.18836281325591042,
                            ExpertMark6 = 0.84697158908979286,
                            ExpertMark7 = 0.21994209625982664,
                            ExpertMark8 = 0.94294766781294848,
                            ExpertMark9 = 0.4547640205017468,
                            Price = 92.627196704020733,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 42,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 25,
                            ExpertMark1 = 0.2162176339701084,
                            ExpertMark10 = 0.063418110672874506,
                            ExpertMark2 = 0.41963973115136066,
                            ExpertMark3 = 0.86761096218362921,
                            ExpertMark4 = 0.15568291601455375,
                            ExpertMark5 = 0.55399767894209517,
                            ExpertMark6 = 0.68559047649856797,
                            ExpertMark7 = 0.86229997656529422,
                            ExpertMark8 = 0.9196358814102974,
                            ExpertMark9 = 0.16150380675166298,
                            Price = 35.971458135956482,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 43,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 26,
                            ExpertMark1 = 0.64684446788814776,
                            ExpertMark10 = 0.058462685415228921,
                            ExpertMark2 = 0.95777324886257875,
                            ExpertMark3 = 0.66237791066391871,
                            ExpertMark4 = 0.87209512275979251,
                            ExpertMark5 = 0.93022067006647402,
                            ExpertMark6 = 0.8898737326685533,
                            ExpertMark7 = 0.78893621854394502,
                            ExpertMark8 = 0.64234641526496661,
                            ExpertMark9 = 0.71064387934318152,
                            Price = 94.503441608644792,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 44,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 27,
                            ExpertMark1 = 0.12482479306686978,
                            ExpertMark10 = 0.2235641846486579,
                            ExpertMark2 = 0.98191278980497632,
                            ExpertMark3 = 0.12543320546584924,
                            ExpertMark4 = 0.6900970590078308,
                            ExpertMark5 = 0.36718105068540152,
                            ExpertMark6 = 0.62131868315529692,
                            ExpertMark7 = 0.2388760809466367,
                            ExpertMark8 = 0.62384391312213616,
                            ExpertMark9 = 0.52415489208008403,
                            Price = 37.336069061699796,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 45,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 28,
                            ExpertMark1 = 0.022827068636111836,
                            ExpertMark10 = 0.91981812875587954,
                            ExpertMark2 = 0.54893065554884468,
                            ExpertMark3 = 0.48524891950406401,
                            ExpertMark4 = 0.32482787213582531,
                            ExpertMark5 = 0.19671540446056757,
                            ExpertMark6 = 0.42536374864738224,
                            ExpertMark7 = 0.025549961164177182,
                            ExpertMark8 = 0.52491762595466696,
                            ExpertMark9 = 0.7095287580476678,
                            Price = 66.412317343830722,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 46,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 29,
                            ExpertMark1 = 0.42535250354555487,
                            ExpertMark10 = 0.76737694139793411,
                            ExpertMark2 = 0.85184403364875005,
                            ExpertMark3 = 0.60744293350458267,
                            ExpertMark4 = 0.81305938578576287,
                            ExpertMark5 = 0.83953687980427338,
                            ExpertMark6 = 0.54985111628977545,
                            ExpertMark7 = 0.38297593954317233,
                            ExpertMark8 = 0.80903210253278035,
                            ExpertMark9 = 0.076745800742850978,
                            Price = 91.853221050425034,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 47,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 30,
                            ExpertMark1 = 0.6765450584631052,
                            ExpertMark10 = 0.45488490073448218,
                            ExpertMark2 = 0.95755230503363087,
                            ExpertMark3 = 0.23911251992343019,
                            ExpertMark4 = 0.73626637795390792,
                            ExpertMark5 = 0.013140477211030621,
                            ExpertMark6 = 0.37622013988771597,
                            ExpertMark7 = 0.046672351236185072,
                            ExpertMark8 = 0.28439793862190998,
                            ExpertMark9 = 0.64202846719693907,
                            Price = 18.168226000707111,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 48,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 31,
                            ExpertMark1 = 0.11121815375320776,
                            ExpertMark10 = 0.20004919802660714,
                            ExpertMark2 = 0.88574899350221481,
                            ExpertMark3 = 0.080242042284279558,
                            ExpertMark4 = 0.25786314509103259,
                            ExpertMark5 = 0.70109664841954888,
                            ExpertMark6 = 0.60240360406880533,
                            ExpertMark7 = 0.79302145712705741,
                            ExpertMark8 = 0.73039631113601855,
                            ExpertMark9 = 0.82513960590390389,
                            Price = 74.063690379604864,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 49,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 32,
                            ExpertMark1 = 0.046355806893729201,
                            ExpertMark10 = 0.42487120353804542,
                            ExpertMark2 = 0.96967153640999848,
                            ExpertMark3 = 0.78335021490575352,
                            ExpertMark4 = 0.18881188601276122,
                            ExpertMark5 = 0.48485996860094582,
                            ExpertMark6 = 0.1331033162651224,
                            ExpertMark7 = 0.3920043108159792,
                            ExpertMark8 = 0.78085636978595263,
                            ExpertMark9 = 0.48017797996190803,
                            Price = 9.6071439520647459,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 50,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 33,
                            ExpertMark1 = 0.30817646754836991,
                            ExpertMark10 = 0.80332241631792889,
                            ExpertMark2 = 0.52522649945405653,
                            ExpertMark3 = 0.92176083082378624,
                            ExpertMark4 = 0.071890078140339986,
                            ExpertMark5 = 0.67397809100858974,
                            ExpertMark6 = 0.98189605370439281,
                            ExpertMark7 = 0.49022215485493392,
                            ExpertMark8 = 0.58737560880087791,
                            ExpertMark9 = 0.53488322175099878,
                            Price = 28.916150692343258,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 51,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 34,
                            ExpertMark1 = 0.56125611661431851,
                            ExpertMark10 = 0.96018482174737663,
                            ExpertMark2 = 0.75997535632860092,
                            ExpertMark3 = 0.44770781645162061,
                            ExpertMark4 = 0.070161136798144619,
                            ExpertMark5 = 0.42291238195423619,
                            ExpertMark6 = 0.71861353670796158,
                            ExpertMark7 = 0.42948660150776297,
                            ExpertMark8 = 0.8054472368593083,
                            ExpertMark9 = 0.78670983822926166,
                            Price = 48.817559881759351,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 52,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 35,
                            ExpertMark1 = 0.4251312330163155,
                            ExpertMark10 = 0.1447194763669567,
                            ExpertMark2 = 0.65369353940196184,
                            ExpertMark3 = 0.18360621521351894,
                            ExpertMark4 = 0.51593490927370822,
                            ExpertMark5 = 0.95366864033527621,
                            ExpertMark6 = 0.21858921225942141,
                            ExpertMark7 = 0.51893468322778635,
                            ExpertMark8 = 0.92004079322544396,
                            ExpertMark9 = 0.11235531376292107,
                            Price = 18.604939738170557,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 53,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 36,
                            ExpertMark1 = 0.42852784238981045,
                            ExpertMark10 = 0.056597763889924435,
                            ExpertMark2 = 0.11848788247043385,
                            ExpertMark3 = 0.66163281299025523,
                            ExpertMark4 = 0.43073010289096303,
                            ExpertMark5 = 0.33144761460909145,
                            ExpertMark6 = 0.21381410375605647,
                            ExpertMark7 = 0.73484841335918616,
                            ExpertMark8 = 0.046612940620437748,
                            ExpertMark9 = 0.32604490979975109,
                            Price = 88.52129015314874,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 54,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 37,
                            ExpertMark1 = 0.99308196851372144,
                            ExpertMark10 = 0.69073200296224202,
                            ExpertMark2 = 0.23951307257273502,
                            ExpertMark3 = 0.72197895410309909,
                            ExpertMark4 = 0.039391699164541438,
                            ExpertMark5 = 0.46141002359305272,
                            ExpertMark6 = 0.86017310645278411,
                            ExpertMark7 = 0.12185125043633571,
                            ExpertMark8 = 0.27128700696197683,
                            ExpertMark9 = 0.83175228473413365,
                            Price = 21.686008860411143,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 55,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 38,
                            ExpertMark1 = 0.63984269404800698,
                            ExpertMark10 = 0.014836782854007136,
                            ExpertMark2 = 0.23652993663874755,
                            ExpertMark3 = 0.86507066868369131,
                            ExpertMark4 = 0.15622456414065711,
                            ExpertMark5 = 0.83873948847712021,
                            ExpertMark6 = 0.47210259241674357,
                            ExpertMark7 = 0.40339422116057777,
                            ExpertMark8 = 0.96604248522744163,
                            ExpertMark9 = 0.17635790955349828,
                            Price = 36.89810062556802,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 56,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 39,
                            ExpertMark1 = 0.63177278503810963,
                            ExpertMark10 = 0.22384068870429097,
                            ExpertMark2 = 0.34110010030969329,
                            ExpertMark3 = 0.5955884939717988,
                            ExpertMark4 = 0.44332267705735096,
                            ExpertMark5 = 0.24799198685599821,
                            ExpertMark6 = 0.71925499942076321,
                            ExpertMark7 = 0.048566784758747761,
                            ExpertMark8 = 0.51632000335568529,
                            ExpertMark9 = 0.94632397268062562,
                            Price = 15.626271483442888,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 57,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 40,
                            ExpertMark1 = 0.83020903136672586,
                            ExpertMark10 = 0.0676437613722769,
                            ExpertMark2 = 0.36750440070608636,
                            ExpertMark3 = 0.23697257183618947,
                            ExpertMark4 = 0.092728322341317893,
                            ExpertMark5 = 0.1159440880645729,
                            ExpertMark6 = 0.83159910004544191,
                            ExpertMark7 = 0.28307600928040499,
                            ExpertMark8 = 0.49864064611278214,
                            ExpertMark9 = 0.3496635394265436,
                            Price = 66.434477306565114,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 58,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 41,
                            ExpertMark1 = 0.33665448480227667,
                            ExpertMark10 = 0.59414863232901494,
                            ExpertMark2 = 0.6522036951835638,
                            ExpertMark3 = 0.18787299628266341,
                            ExpertMark4 = 0.7807589579658949,
                            ExpertMark5 = 0.58478036025494651,
                            ExpertMark6 = 0.84935374996278334,
                            ExpertMark7 = 0.63474907483875298,
                            ExpertMark8 = 0.063462948342927428,
                            ExpertMark9 = 0.20620838247093631,
                            Price = 83.506961199073672,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 59,
                            Summary = 0.0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpertCoef1")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef10")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef2")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef3")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef4")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef5")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef6")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef7")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef8")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef9")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Summary")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskExpertMarksCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            Name = "Множина настання технічних ризикових подій",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            Name = "Множина настання вартісних ризикових подій",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            Name = "Множина настання планових ризикових подій",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.HasOne("AppRisks.Models.RiskCategory", "RiskCategory")
                        .WithMany("Risks")
                        .HasForeignKey("RiskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.HasOne("AppRisks.Models.RiskExpertMarksCategory", "RiskExpertMarksCategory")
                        .WithMany("RiskExpertMarksList")
                        .HasForeignKey("RiskExpertMarksCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppRisks.Models.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("RiskExpertMarksCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Navigation("RiskExpertMarksList");
                });
#pragma warning restore 612, 618
        }
    }
}
