// <auto-generated />
using AppRisks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppRisks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221117223801_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskCategoryId");

                    b.ToTable("Risks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Функціональні характеристики ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Характеристики якості ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Характеристики надійності ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Застосовність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Часова продуктивність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Супроводжуваність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Повторне використання компонент ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Обмеження сумарного бюджету на програмний продукт",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Недоступна вартість реалізації програмного проекту",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Низька ступінь реалізму при оцінюванні витрат на програмний проект",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "Властивості та можливості гнучкості внесення змін до планів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            Content = "Можливості порушення встановлених термінів реалізації етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            Content = "Низька ступінь реалізму при встановленні планів і етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Хибна стратегія реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "Неефективне планування проекту розроблення ПЗ",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Неякісне оцінювання програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 17,
                            Content = "Прогалини в документуванні етапів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 18,
                            Content = "Промахи в прогнозуванні результатів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 19,
                            Content = "Затримки у постачанні обладнання, необхідного для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "Затримки у постачанні інструментальних засобів, необхідних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Небажання команди виконавців використовувати інструментальні засоби для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Content = "Формування запитів на більш потужні інструментальні засоби розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "Відмова команди виконавців від CASE-засобів розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 24,
                            Content = "Неефективність програмного коду, згенерованого CASE-засобами розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 25,
                            Content = "Неможливість інтеграції CASE-засобів з іншими інструментальними засобами для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "Недостатня продуктивність баз(и) даних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 27,
                            Content = "Програмні компоненти, які використовують повторно в ПЗ, мають дефекти та обмежені функціональні можливості",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "Швидкість виявлення дефектів у програмному коді є нижчою від раніше запланованих термінів",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 29,
                            Content = "Поява дефектних системних компонент, які використовують для розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Content = "Недо(пере)оцінювання витрат на реалізацію програмного проекту (надмірно низька вартість)",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 31,
                            Content = "Фінансові ускладнення у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 32,
                            Content = "Фінансові ускладнення у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 33,
                            Content = "Змен(збіль)шення бюджету програмного проекта з ініціативи компанії-замовника ПЗ під час його реалізації",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            Content = "Висока вартість виконання повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 35,
                            Content = "Реорганізація структурних підрозділів у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 36,
                            Content = "Реорганізація команди виконавців у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 37,
                            Content = "Зміни графіка виконання робіт з боку замовника чи розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            Content = "Порушення графіка виконання робіт з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 39,
                            Content = "Потреба зміни користувацьких вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 40,
                            Content = "Потреба зміни функціональних вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 41,
                            Content = "Потреба виконання великої кількості повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 42,
                            Content = "Недо(пере)оцінювання тривалості етапів реалізації програмного проекту з боку компанії-замовника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 43,
                            Content = "Остаточний розмір ПЗ значно перевищує (менший від) заплановані(их) його характеристики",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 44,
                            Content = "Поява на ринку аналогічного ПЗ до виходу замовленого",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 45,
                            Content = "Поява на ринку більш конкурентоздатного ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 46,
                            Content = "Низький моральний стан персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 47,
                            Content = "Низька взаємодія між членами команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 48,
                            Content = "Пасивність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 49,
                            Content = "Недостатня компетентність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 50,
                            Content = "Незадоволеність замовника результатами етапів реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 51,
                            Content = "Недостатня кількість фахівців у команді виконавців ПЗ з необхідним професійним рівнем",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 52,
                            Content = "Хвороба провідного виконавця в найкритичніший момент розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 53,
                            Content = "Одночасна хвороба декількох виконавців підчас розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 54,
                            Content = "Неможливість організації необхідного навчання персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 55,
                            Content = "Зміна пріоритетів у процесі управління програмним проектом",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "Недо(пере)оцінювання необхідної кількості розробників (підрядників і субпідрядників) на етапах життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 57,
                            Content = "Недостатнє (надмірне) документування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 58,
                            Content = "Нереалістичне прогнозування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 59,
                            Content = "Недостатній професійний рівень представників від компанії-замовника ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Множина джерел появи технічних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Множина джерел появи вартісних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Множина джерел появи планових ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Множина джерел появи ризиків реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Множина настання технічних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Множина настання вартісних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Множина настання планових ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpertCoef1")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef10")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef2")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef3")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef4")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef5")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef6")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef7")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef8")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef9")
                        .HasColumnType("int");

                    b.Property<double>("ExpertMark1")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark10")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark2")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark3")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark4")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark5")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark6")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark7")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark8")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark9")
                        .HasColumnType("float");

                    b.Property<int>("RiskExpertMarksCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskExpertMarksCategoryId");

                    b.HasIndex("RiskId");

                    b.ToTable("RiskExpertMarksEnumerable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.35380445722169307,
                            ExpertMark10 = 0.54236653905694432,
                            ExpertMark2 = 0.076550016525822717,
                            ExpertMark3 = 0.53784549339483112,
                            ExpertMark4 = 0.50956086978338411,
                            ExpertMark5 = 0.43650886699466851,
                            ExpertMark6 = 0.037724997702192509,
                            ExpertMark7 = 0.81481506773848733,
                            ExpertMark8 = 0.42587655101719513,
                            ExpertMark9 = 0.11353957450823871,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 19
                        },
                        new
                        {
                            Id = 2,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.37198721675257163,
                            ExpertMark10 = 0.36272841848731452,
                            ExpertMark2 = 0.94511254786065269,
                            ExpertMark3 = 0.95999047372901591,
                            ExpertMark4 = 0.18912799206524733,
                            ExpertMark5 = 0.17708394561514451,
                            ExpertMark6 = 0.066334149690527866,
                            ExpertMark7 = 0.70220168286419771,
                            ExpertMark8 = 0.49576397490816781,
                            ExpertMark9 = 0.76756233876418567,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 20
                        },
                        new
                        {
                            Id = 3,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.11505827129223223,
                            ExpertMark10 = 0.95307871470921401,
                            ExpertMark2 = 0.69790108311827348,
                            ExpertMark3 = 0.42063116407622714,
                            ExpertMark4 = 0.97708500360798356,
                            ExpertMark5 = 0.44848842760208107,
                            ExpertMark6 = 0.77858214759367084,
                            ExpertMark7 = 0.013692910711102901,
                            ExpertMark8 = 0.6112641450111771,
                            ExpertMark9 = 0.24241518526465955,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 21
                        },
                        new
                        {
                            Id = 4,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.36381725873066606,
                            ExpertMark10 = 0.28337173347288358,
                            ExpertMark2 = 0.83192476416476302,
                            ExpertMark3 = 0.26587437878865006,
                            ExpertMark4 = 0.69723951352584201,
                            ExpertMark5 = 0.071020703858323708,
                            ExpertMark6 = 0.60033976185806825,
                            ExpertMark7 = 0.64389511165016955,
                            ExpertMark8 = 0.66182760296097687,
                            ExpertMark9 = 0.99052580656708,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 22
                        },
                        new
                        {
                            Id = 5,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.72954868309249643,
                            ExpertMark10 = 0.92246436133164789,
                            ExpertMark2 = 0.5572994519284401,
                            ExpertMark3 = 0.62128446324038933,
                            ExpertMark4 = 0.87300359529588734,
                            ExpertMark5 = 0.73075459141469634,
                            ExpertMark6 = 0.34437156475162367,
                            ExpertMark7 = 0.88647123405757433,
                            ExpertMark8 = 0.99050657477426396,
                            ExpertMark9 = 0.61191722802598991,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 23
                        },
                        new
                        {
                            Id = 6,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.52840899152759835,
                            ExpertMark10 = 0.16086172142319954,
                            ExpertMark2 = 0.10165002170436654,
                            ExpertMark3 = 0.62110713194069855,
                            ExpertMark4 = 0.81839356076655467,
                            ExpertMark5 = 0.79427179702733886,
                            ExpertMark6 = 0.51666724258058649,
                            ExpertMark7 = 0.70793028666098146,
                            ExpertMark8 = 0.76266925567196742,
                            ExpertMark9 = 0.63339272661809543,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 24
                        },
                        new
                        {
                            Id = 7,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.62252595290175716,
                            ExpertMark10 = 0.019764474861934334,
                            ExpertMark2 = 0.67084343876936603,
                            ExpertMark3 = 0.28748377320804064,
                            ExpertMark4 = 0.51375507737034798,
                            ExpertMark5 = 0.77448095821561447,
                            ExpertMark6 = 0.056255246731237496,
                            ExpertMark7 = 0.026445062117048224,
                            ExpertMark8 = 0.98316542487571679,
                            ExpertMark9 = 0.6441686298000675,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 25
                        },
                        new
                        {
                            Id = 8,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.27784022193049096,
                            ExpertMark10 = 0.83861113110929186,
                            ExpertMark2 = 0.37227942990271712,
                            ExpertMark3 = 0.085909467661357319,
                            ExpertMark4 = 0.6849899266908398,
                            ExpertMark5 = 0.28841482401291041,
                            ExpertMark6 = 0.28712590254423953,
                            ExpertMark7 = 0.20607612927597541,
                            ExpertMark8 = 0.41565105801744995,
                            ExpertMark9 = 0.096808715179176996,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 26
                        },
                        new
                        {
                            Id = 9,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.61384149353939377,
                            ExpertMark10 = 0.98436378227910371,
                            ExpertMark2 = 0.67575808120717173,
                            ExpertMark3 = 0.082485564721867743,
                            ExpertMark4 = 0.92319204827640811,
                            ExpertMark5 = 0.7730250711692902,
                            ExpertMark6 = 0.5516929642047429,
                            ExpertMark7 = 0.59739301110125209,
                            ExpertMark8 = 0.23304435487847608,
                            ExpertMark9 = 0.55919659488843443,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 27
                        },
                        new
                        {
                            Id = 10,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.94363434370754551,
                            ExpertMark10 = 0.22998336602070957,
                            ExpertMark2 = 0.60536003773327229,
                            ExpertMark3 = 0.24617947253575945,
                            ExpertMark4 = 0.9960382998938051,
                            ExpertMark5 = 0.99256521834307421,
                            ExpertMark6 = 0.43236638702916719,
                            ExpertMark7 = 0.060915802481054659,
                            ExpertMark8 = 0.45351452741724807,
                            ExpertMark9 = 0.81629471205658255,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 28
                        },
                        new
                        {
                            Id = 11,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            ExpertMark1 = 0.82836011390563591,
                            ExpertMark10 = 0.464722192016637,
                            ExpertMark2 = 0.83970959882881602,
                            ExpertMark3 = 0.14879323608697348,
                            ExpertMark4 = 0.39108675974288576,
                            ExpertMark5 = 0.87315604759565979,
                            ExpertMark6 = 0.66825992215687025,
                            ExpertMark7 = 0.43575425900019038,
                            ExpertMark8 = 0.83796414469522407,
                            ExpertMark9 = 0.29384217086924613,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 29
                        },
                        new
                        {
                            Id = 12,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            ExpertMark1 = 0.32268119722132538,
                            ExpertMark10 = 0.91111058880175155,
                            ExpertMark2 = 0.88762407637149321,
                            ExpertMark3 = 0.1427840281366235,
                            ExpertMark4 = 0.3123647167926249,
                            ExpertMark5 = 0.75872526776775884,
                            ExpertMark6 = 0.21703648226267747,
                            ExpertMark7 = 0.90328372539047441,
                            ExpertMark8 = 0.26400176668776987,
                            ExpertMark9 = 0.61184452866644212,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 30
                        },
                        new
                        {
                            Id = 13,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            ExpertMark1 = 0.99468994420526491,
                            ExpertMark10 = 0.038570537809909822,
                            ExpertMark2 = 0.60209022474868745,
                            ExpertMark3 = 0.21407490515598715,
                            ExpertMark4 = 0.5445359584506031,
                            ExpertMark5 = 0.67924076945890499,
                            ExpertMark6 = 0.19434340571159436,
                            ExpertMark7 = 0.19109262050783304,
                            ExpertMark8 = 0.45151769132177799,
                            ExpertMark9 = 0.21699043139231855,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 31
                        },
                        new
                        {
                            Id = 14,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            ExpertMark1 = 0.17829943854662789,
                            ExpertMark10 = 0.95011259619848876,
                            ExpertMark2 = 0.67737523866625882,
                            ExpertMark3 = 0.33562366495033125,
                            ExpertMark4 = 0.77429898058737534,
                            ExpertMark5 = 0.90717911120936723,
                            ExpertMark6 = 0.29967945429198894,
                            ExpertMark7 = 0.98986904836338119,
                            ExpertMark8 = 0.78427201040556493,
                            ExpertMark9 = 0.5670088184241876,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 32
                        },
                        new
                        {
                            Id = 15,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            ExpertMark1 = 0.62764891205365303,
                            ExpertMark10 = 0.54631026044288811,
                            ExpertMark2 = 0.28344296239177902,
                            ExpertMark3 = 0.6669702951204145,
                            ExpertMark4 = 0.17673501120644308,
                            ExpertMark5 = 0.4989221966618218,
                            ExpertMark6 = 0.021093181366331759,
                            ExpertMark7 = 0.39610497643612863,
                            ExpertMark8 = 0.68827936228689357,
                            ExpertMark9 = 0.1740552528910484,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 33
                        },
                        new
                        {
                            Id = 16,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            ExpertMark1 = 0.77298207019443599,
                            ExpertMark10 = 0.22221222211840341,
                            ExpertMark2 = 0.73943795466800855,
                            ExpertMark3 = 0.92030937598792739,
                            ExpertMark4 = 0.23071978338882315,
                            ExpertMark5 = 0.18501210718359551,
                            ExpertMark6 = 0.55958169577855132,
                            ExpertMark7 = 0.20645058839666741,
                            ExpertMark8 = 0.90328629894995061,
                            ExpertMark9 = 0.66737687863049588,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 34
                        },
                        new
                        {
                            Id = 17,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            ExpertMark1 = 0.99279052755198494,
                            ExpertMark10 = 0.22263878082538158,
                            ExpertMark2 = 0.88281810380358017,
                            ExpertMark3 = 0.37927816269649117,
                            ExpertMark4 = 0.48780069483462574,
                            ExpertMark5 = 0.62859814227440558,
                            ExpertMark6 = 0.48006876697477308,
                            ExpertMark7 = 0.44791948924495917,
                            ExpertMark8 = 0.58244431211795322,
                            ExpertMark9 = 0.18928912929222796,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 35
                        },
                        new
                        {
                            Id = 18,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            ExpertMark1 = 0.84851965822399567,
                            ExpertMark10 = 0.93554509782160367,
                            ExpertMark2 = 0.84538972627517128,
                            ExpertMark3 = 0.68340871215341126,
                            ExpertMark4 = 0.069744708082267071,
                            ExpertMark5 = 0.3798723945214999,
                            ExpertMark6 = 0.53653967050573936,
                            ExpertMark7 = 0.77963106458146225,
                            ExpertMark8 = 0.47146504656573929,
                            ExpertMark9 = 0.28025371978811797,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 36
                        },
                        new
                        {
                            Id = 19,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.092035784174199997,
                            ExpertMark10 = 0.4666685384213074,
                            ExpertMark2 = 0.96028994275902801,
                            ExpertMark3 = 0.72692090662172715,
                            ExpertMark4 = 0.53134300310509253,
                            ExpertMark5 = 0.22239428631271196,
                            ExpertMark6 = 0.94369805105152305,
                            ExpertMark7 = 0.30761846570770413,
                            ExpertMark8 = 0.61391576972788287,
                            ExpertMark9 = 0.65003792490029166,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 37
                        },
                        new
                        {
                            Id = 20,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.77097344769064602,
                            ExpertMark10 = 0.072529056878351428,
                            ExpertMark2 = 0.50440093541305764,
                            ExpertMark3 = 0.012042167700961781,
                            ExpertMark4 = 0.94499682110501115,
                            ExpertMark5 = 0.69231328588100183,
                            ExpertMark6 = 0.65000329663103551,
                            ExpertMark7 = 0.30122001830179534,
                            ExpertMark8 = 0.97473677621941168,
                            ExpertMark9 = 0.18518725473125053,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 38
                        },
                        new
                        {
                            Id = 21,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.89384516072969311,
                            ExpertMark10 = 0.58042225834265426,
                            ExpertMark2 = 0.71157942944688968,
                            ExpertMark3 = 0.64665288206403082,
                            ExpertMark4 = 0.87297536693031363,
                            ExpertMark5 = 0.79258426720498554,
                            ExpertMark6 = 0.1509095039840328,
                            ExpertMark7 = 0.63514678195299445,
                            ExpertMark8 = 0.71437786785601631,
                            ExpertMark9 = 0.27190181350454723,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 39
                        },
                        new
                        {
                            Id = 22,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.41633117303511202,
                            ExpertMark10 = 0.43925004582879834,
                            ExpertMark2 = 0.84168207580107102,
                            ExpertMark3 = 0.66338285325016588,
                            ExpertMark4 = 0.97293820815919407,
                            ExpertMark5 = 0.68541964431749014,
                            ExpertMark6 = 0.24226721271778395,
                            ExpertMark7 = 0.61112875302188896,
                            ExpertMark8 = 0.68359331551583635,
                            ExpertMark9 = 0.36454698734431334,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 40
                        },
                        new
                        {
                            Id = 23,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.39771131403476168,
                            ExpertMark10 = 0.24200317043570285,
                            ExpertMark2 = 0.45699206351646504,
                            ExpertMark3 = 0.78495438804534146,
                            ExpertMark4 = 0.36336936464951786,
                            ExpertMark5 = 0.10120902880651672,
                            ExpertMark6 = 0.56911073756379371,
                            ExpertMark7 = 0.61685075832450909,
                            ExpertMark8 = 0.19471410579039838,
                            ExpertMark9 = 0.68541824444439181,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 41
                        },
                        new
                        {
                            Id = 24,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.69446403042549154,
                            ExpertMark10 = 0.54646842155221209,
                            ExpertMark2 = 0.21052714339213074,
                            ExpertMark3 = 0.11474958558289172,
                            ExpertMark4 = 0.56589067137973459,
                            ExpertMark5 = 0.094395965469434184,
                            ExpertMark6 = 0.4831286342254596,
                            ExpertMark7 = 0.90288950731193185,
                            ExpertMark8 = 0.97792343848396324,
                            ExpertMark9 = 0.11739792306608188,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 42
                        },
                        new
                        {
                            Id = 25,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.60892000337265983,
                            ExpertMark10 = 0.077496384165947729,
                            ExpertMark2 = 0.37621468717840445,
                            ExpertMark3 = 0.97427371248000794,
                            ExpertMark4 = 0.83998855098802938,
                            ExpertMark5 = 0.98490239633518262,
                            ExpertMark6 = 0.28512880719664724,
                            ExpertMark7 = 0.095887113019015979,
                            ExpertMark8 = 0.69070924841240156,
                            ExpertMark9 = 0.51552545372351655,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 43
                        },
                        new
                        {
                            Id = 26,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.90566645303939852,
                            ExpertMark10 = 0.36073598762535253,
                            ExpertMark2 = 0.0065032860101075229,
                            ExpertMark3 = 0.10880985587690917,
                            ExpertMark4 = 0.8303695768155771,
                            ExpertMark5 = 0.19667404739162997,
                            ExpertMark6 = 0.60857146762483549,
                            ExpertMark7 = 0.88775572769016275,
                            ExpertMark8 = 0.62998165694560015,
                            ExpertMark9 = 0.86197764024505041,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 44
                        },
                        new
                        {
                            Id = 27,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            ExpertMark1 = 0.86402982973301801,
                            ExpertMark10 = 0.40275672843922117,
                            ExpertMark2 = 0.48572723629738535,
                            ExpertMark3 = 0.43388277782116713,
                            ExpertMark4 = 0.19239529593683735,
                            ExpertMark5 = 0.44973316057465262,
                            ExpertMark6 = 0.61702259738225484,
                            ExpertMark7 = 0.35950491589529177,
                            ExpertMark8 = 0.48410906440845114,
                            ExpertMark9 = 0.8326141913729338,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 45
                        },
                        new
                        {
                            Id = 28,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.30646092787715318,
                            ExpertMark10 = 0.54049172653248501,
                            ExpertMark2 = 0.56245291036607092,
                            ExpertMark3 = 0.34241674143107925,
                            ExpertMark4 = 0.65887075330335665,
                            ExpertMark5 = 0.66026096442887161,
                            ExpertMark6 = 0.98804502326480326,
                            ExpertMark7 = 0.47620955827615641,
                            ExpertMark8 = 0.35376919990749744,
                            ExpertMark9 = 0.59607182158967553,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 46
                        },
                        new
                        {
                            Id = 29,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.75378773920865272,
                            ExpertMark10 = 0.72041065997288778,
                            ExpertMark2 = 0.34305222408397795,
                            ExpertMark3 = 0.69162062032800231,
                            ExpertMark4 = 0.61863333239187357,
                            ExpertMark5 = 0.071329495757306627,
                            ExpertMark6 = 0.18274293399066988,
                            ExpertMark7 = 0.5721445498491996,
                            ExpertMark8 = 0.64901306873081743,
                            ExpertMark9 = 0.67783841971179304,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 47
                        },
                        new
                        {
                            Id = 30,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.75740830715466745,
                            ExpertMark10 = 0.63661630514387124,
                            ExpertMark2 = 0.68329151987517989,
                            ExpertMark3 = 0.51049976772610117,
                            ExpertMark4 = 0.18920409969324903,
                            ExpertMark5 = 0.58617605378231163,
                            ExpertMark6 = 0.81031683877884253,
                            ExpertMark7 = 0.37159670130038325,
                            ExpertMark8 = 0.62304049495647951,
                            ExpertMark9 = 0.17022904983953968,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 48
                        },
                        new
                        {
                            Id = 31,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.38862590759550719,
                            ExpertMark10 = 0.84421409336670983,
                            ExpertMark2 = 0.27874989235968839,
                            ExpertMark3 = 0.60649546869613558,
                            ExpertMark4 = 0.062170254325724428,
                            ExpertMark5 = 0.38581867556944527,
                            ExpertMark6 = 0.50015255385608537,
                            ExpertMark7 = 0.36084676884777867,
                            ExpertMark8 = 0.77841337374493835,
                            ExpertMark9 = 0.32438364585926305,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 49
                        },
                        new
                        {
                            Id = 32,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.11734313381250283,
                            ExpertMark10 = 0.61371491232310038,
                            ExpertMark2 = 0.88745187741011899,
                            ExpertMark3 = 0.12857025229029584,
                            ExpertMark4 = 0.28142441067042345,
                            ExpertMark5 = 0.081640395407447053,
                            ExpertMark6 = 0.75429624422874408,
                            ExpertMark7 = 0.6258211626682374,
                            ExpertMark8 = 0.0028636390764326114,
                            ExpertMark9 = 0.98077682212662565,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 50
                        },
                        new
                        {
                            Id = 33,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.78557533072604557,
                            ExpertMark10 = 0.72223130941911162,
                            ExpertMark2 = 0.88033413004884342,
                            ExpertMark3 = 0.10878786700484877,
                            ExpertMark4 = 0.81070617807849299,
                            ExpertMark5 = 0.63117266420598173,
                            ExpertMark6 = 0.79415869793467542,
                            ExpertMark7 = 0.11961972014834221,
                            ExpertMark8 = 0.13059635060439001,
                            ExpertMark9 = 0.17545776032000016,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 51
                        },
                        new
                        {
                            Id = 34,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.53267487467566699,
                            ExpertMark10 = 0.49669230140290843,
                            ExpertMark2 = 0.0094557654897774457,
                            ExpertMark3 = 0.21821322903163787,
                            ExpertMark4 = 0.9440911358027102,
                            ExpertMark5 = 0.43640902264958392,
                            ExpertMark6 = 0.12087658702749038,
                            ExpertMark7 = 0.23105357007826166,
                            ExpertMark8 = 0.24926871444079035,
                            ExpertMark9 = 0.041696962357496536,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 52
                        },
                        new
                        {
                            Id = 35,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.70964003951355537,
                            ExpertMark10 = 0.019015736537460803,
                            ExpertMark2 = 0.16699225924665873,
                            ExpertMark3 = 0.98821846816401604,
                            ExpertMark4 = 0.67710368685476208,
                            ExpertMark5 = 0.14947112328558987,
                            ExpertMark6 = 0.66009572122233762,
                            ExpertMark7 = 0.22119360865334292,
                            ExpertMark8 = 0.21001148212829068,
                            ExpertMark9 = 0.98749898042138295,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 53
                        },
                        new
                        {
                            Id = 36,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.87686583002574214,
                            ExpertMark10 = 0.45967414352819869,
                            ExpertMark2 = 0.31178869902967388,
                            ExpertMark3 = 0.34684699077270209,
                            ExpertMark4 = 0.18785731991904941,
                            ExpertMark5 = 0.81561727656672667,
                            ExpertMark6 = 0.13500541442313507,
                            ExpertMark7 = 0.28825800886050401,
                            ExpertMark8 = 0.10524853771779885,
                            ExpertMark9 = 0.67356008553830804,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 54
                        },
                        new
                        {
                            Id = 37,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.010168585600887847,
                            ExpertMark10 = 0.58598059583997153,
                            ExpertMark2 = 0.69243861657375616,
                            ExpertMark3 = 0.082348025881755271,
                            ExpertMark4 = 0.54001818814323943,
                            ExpertMark5 = 0.46213011041057905,
                            ExpertMark6 = 0.19829534830915518,
                            ExpertMark7 = 0.71842861325315233,
                            ExpertMark8 = 0.31468987464068521,
                            ExpertMark9 = 0.7803118939701541,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 55
                        },
                        new
                        {
                            Id = 38,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.52241754436382015,
                            ExpertMark10 = 0.12003579358394967,
                            ExpertMark2 = 0.34124257194456042,
                            ExpertMark3 = 0.74105216088112269,
                            ExpertMark4 = 0.38004593430124511,
                            ExpertMark5 = 0.31829965014056272,
                            ExpertMark6 = 0.34942995337446636,
                            ExpertMark7 = 0.22266182542327917,
                            ExpertMark8 = 0.7799140287251648,
                            ExpertMark9 = 0.53378800020925632,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 56
                        },
                        new
                        {
                            Id = 39,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.72172340685095682,
                            ExpertMark10 = 0.16080844873081035,
                            ExpertMark2 = 0.0024640467006342703,
                            ExpertMark3 = 0.94835846326740891,
                            ExpertMark4 = 0.089002632932777215,
                            ExpertMark5 = 0.2585878159989079,
                            ExpertMark6 = 0.26208859654035055,
                            ExpertMark7 = 0.74327696393732978,
                            ExpertMark8 = 0.94617291406509141,
                            ExpertMark9 = 0.6342115949038224,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 57
                        },
                        new
                        {
                            Id = 40,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.32965660627102467,
                            ExpertMark10 = 0.51924995346704728,
                            ExpertMark2 = 0.63199781105197461,
                            ExpertMark3 = 0.8679702007638691,
                            ExpertMark4 = 0.95621465425004626,
                            ExpertMark5 = 0.75141547185227509,
                            ExpertMark6 = 0.71112294438430246,
                            ExpertMark7 = 0.2940143166341378,
                            ExpertMark8 = 0.70484391772123023,
                            ExpertMark9 = 0.32406592015300195,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 58
                        },
                        new
                        {
                            Id = 41,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            ExpertMark1 = 0.69796553973757847,
                            ExpertMark10 = 0.45476728502325192,
                            ExpertMark2 = 0.3393714045795434,
                            ExpertMark3 = 0.17896663987789019,
                            ExpertMark4 = 0.44465757190608635,
                            ExpertMark5 = 0.64212260993420323,
                            ExpertMark6 = 0.98536409220178156,
                            ExpertMark7 = 0.77411836447198845,
                            ExpertMark8 = 0.22467700114225309,
                            ExpertMark9 = 0.14380494264368637,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 59
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RiskExpertMarksCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Множина настання технічних ризикових подій"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Множина настання вартісних ризикових подій"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Множина настання планових ризикових подій"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом"
                        });
                });

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.HasOne("AppRisks.Models.RiskCategory", "RiskCategory")
                        .WithMany("Risks")
                        .HasForeignKey("RiskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.HasOne("AppRisks.Models.RiskExpertMarksCategory", "RiskExpertMarksCategory")
                        .WithMany("RiskExpertMarksList")
                        .HasForeignKey("RiskExpertMarksCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppRisks.Models.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("RiskExpertMarksCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Navigation("RiskExpertMarksList");
                });
#pragma warning restore 612, 618
        }
    }
}
