// <auto-generated />
using AppRisks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppRisks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221118174136_AddWeighedMarks")]
    partial class AddWeighedMarks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskCategoryId");

                    b.ToTable("Risks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Функціональні характеристики ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Характеристики якості ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Характеристики надійності ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Застосовність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Часова продуктивність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Супроводжуваність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Повторне використання компонент ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Обмеження сумарного бюджету на програмний продукт",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Недоступна вартість реалізації програмного проекту",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Низька ступінь реалізму при оцінюванні витрат на програмний проект",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "Властивості та можливості гнучкості внесення змін до планів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            Content = "Можливості порушення встановлених термінів реалізації етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            Content = "Низька ступінь реалізму при встановленні планів і етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Хибна стратегія реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "Неефективне планування проекту розроблення ПЗ",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Неякісне оцінювання програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 17,
                            Content = "Прогалини в документуванні етапів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 18,
                            Content = "Промахи в прогнозуванні результатів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 19,
                            Content = "Затримки у постачанні обладнання, необхідного для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "Затримки у постачанні інструментальних засобів, необхідних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Небажання команди виконавців використовувати інструментальні засоби для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Content = "Формування запитів на більш потужні інструментальні засоби розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "Відмова команди виконавців від CASE-засобів розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 24,
                            Content = "Неефективність програмного коду, згенерованого CASE-засобами розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 25,
                            Content = "Неможливість інтеграції CASE-засобів з іншими інструментальними засобами для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "Недостатня продуктивність баз(и) даних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 27,
                            Content = "Програмні компоненти, які використовують повторно в ПЗ, мають дефекти та обмежені функціональні можливості",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "Швидкість виявлення дефектів у програмному коді є нижчою від раніше запланованих термінів",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 29,
                            Content = "Поява дефектних системних компонент, які використовують для розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Content = "Недо(пере)оцінювання витрат на реалізацію програмного проекту (надмірно низька вартість)",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 31,
                            Content = "Фінансові ускладнення у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 32,
                            Content = "Фінансові ускладнення у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 33,
                            Content = "Змен(збіль)шення бюджету програмного проекта з ініціативи компанії-замовника ПЗ під час його реалізації",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            Content = "Висока вартість виконання повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 35,
                            Content = "Реорганізація структурних підрозділів у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 36,
                            Content = "Реорганізація команди виконавців у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 37,
                            Content = "Зміни графіка виконання робіт з боку замовника чи розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            Content = "Порушення графіка виконання робіт з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 39,
                            Content = "Потреба зміни користувацьких вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 40,
                            Content = "Потреба зміни функціональних вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 41,
                            Content = "Потреба виконання великої кількості повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 42,
                            Content = "Недо(пере)оцінювання тривалості етапів реалізації програмного проекту з боку компанії-замовника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 43,
                            Content = "Остаточний розмір ПЗ значно перевищує (менший від) заплановані(их) його характеристики",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 44,
                            Content = "Поява на ринку аналогічного ПЗ до виходу замовленого",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 45,
                            Content = "Поява на ринку більш конкурентоздатного ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 46,
                            Content = "Низький моральний стан персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 47,
                            Content = "Низька взаємодія між членами команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 48,
                            Content = "Пасивність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 49,
                            Content = "Недостатня компетентність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 50,
                            Content = "Незадоволеність замовника результатами етапів реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 51,
                            Content = "Недостатня кількість фахівців у команді виконавців ПЗ з необхідним професійним рівнем",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 52,
                            Content = "Хвороба провідного виконавця в найкритичніший момент розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 53,
                            Content = "Одночасна хвороба декількох виконавців підчас розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 54,
                            Content = "Неможливість організації необхідного навчання персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 55,
                            Content = "Зміна пріоритетів у процесі управління програмним проектом",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "Недо(пере)оцінювання необхідної кількості розробників (підрядників і субпідрядників) на етапах життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 57,
                            Content = "Недостатнє (надмірне) документування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 58,
                            Content = "Нереалістичне прогнозування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 59,
                            Content = "Недостатній професійний рівень представників від компанії-замовника ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Множина джерел появи технічних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Множина джерел появи вартісних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Множина джерел появи планових ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Множина джерел появи ризиків реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Множина настання технічних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Множина настання вартісних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Множина настання планових ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ExpertMark1")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark10")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark2")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark3")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark4")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark5")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark6")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark7")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark8")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark9")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed1")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed10")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed2")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed3")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed4")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed5")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed6")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed7")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed8")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMarkWeighed9")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RiskExpertMarksCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.Property<double>("Summary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RiskExpertMarksCategoryId");

                    b.HasIndex("RiskId");

                    b.ToTable("RiskExpertMarksEnumerable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertMark1 = 0.20816622117902428,
                            ExpertMark10 = 0.35516473663183024,
                            ExpertMark2 = 0.30328908608885996,
                            ExpertMark3 = 0.56035707846547589,
                            ExpertMark4 = 0.0560562210761264,
                            ExpertMark5 = 0.2735827353273268,
                            ExpertMark6 = 0.80477298364731553,
                            ExpertMark7 = 0.38840084875784764,
                            ExpertMark8 = 0.071484387542028238,
                            ExpertMark9 = 0.13118118174626403,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 97.138045363590152,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 19,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 2,
                            ExpertMark1 = 0.12008921702958875,
                            ExpertMark10 = 0.28991668768648959,
                            ExpertMark2 = 0.37907227305039648,
                            ExpertMark3 = 0.84636481626524862,
                            ExpertMark4 = 0.37458556309617341,
                            ExpertMark5 = 0.66983539186198571,
                            ExpertMark6 = 0.55421488560044907,
                            ExpertMark7 = 0.57087055207180171,
                            ExpertMark8 = 0.28452169930659021,
                            ExpertMark9 = 0.40722238143457812,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 49.478628000473954,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 20,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 3,
                            ExpertMark1 = 0.91929396122749352,
                            ExpertMark10 = 0.44335143577818181,
                            ExpertMark2 = 0.65684457212504543,
                            ExpertMark3 = 0.41687041550592352,
                            ExpertMark4 = 0.99183718225651862,
                            ExpertMark5 = 0.4180235266357869,
                            ExpertMark6 = 0.71712187204774824,
                            ExpertMark7 = 0.44101767083508137,
                            ExpertMark8 = 0.92947061248585305,
                            ExpertMark9 = 0.53202050785785215,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 35.323015053612373,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 21,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 4,
                            ExpertMark1 = 0.94977899462269855,
                            ExpertMark10 = 0.47986607875745024,
                            ExpertMark2 = 0.78430599833567827,
                            ExpertMark3 = 0.8016144259219079,
                            ExpertMark4 = 0.59738048504395491,
                            ExpertMark5 = 0.58087613301877605,
                            ExpertMark6 = 0.19451086937976125,
                            ExpertMark7 = 0.42395184206663061,
                            ExpertMark8 = 0.89416712768990803,
                            ExpertMark9 = 0.87742414122781764,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 14.70527241996048,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 22,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 5,
                            ExpertMark1 = 0.27943016298321999,
                            ExpertMark10 = 0.79561497788014512,
                            ExpertMark2 = 0.33450675504778038,
                            ExpertMark3 = 0.74347677411467405,
                            ExpertMark4 = 0.76661272832407179,
                            ExpertMark5 = 0.41865569168577288,
                            ExpertMark6 = 0.35521169647644024,
                            ExpertMark7 = 0.75996865279244852,
                            ExpertMark8 = 0.79346801254720511,
                            ExpertMark9 = 0.76177280469643349,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 26.940237640749586,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 23,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 6,
                            ExpertMark1 = 0.86719659099909907,
                            ExpertMark10 = 0.5811442432676257,
                            ExpertMark2 = 0.26053265956529192,
                            ExpertMark3 = 0.012021855097339551,
                            ExpertMark4 = 0.12906131668005361,
                            ExpertMark5 = 0.86835461630390298,
                            ExpertMark6 = 0.047011779609083759,
                            ExpertMark7 = 0.98739783152132787,
                            ExpertMark8 = 0.5111416001468766,
                            ExpertMark9 = 0.1523069003433436,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 21.736514584074364,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 24,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 7,
                            ExpertMark1 = 0.46803197653462625,
                            ExpertMark10 = 0.83618455479948273,
                            ExpertMark2 = 0.88428183205904998,
                            ExpertMark3 = 0.32763233128925606,
                            ExpertMark4 = 0.51077474100359266,
                            ExpertMark5 = 0.76648311050426765,
                            ExpertMark6 = 0.40039261487115019,
                            ExpertMark7 = 0.92289867692693461,
                            ExpertMark8 = 0.54972261146907353,
                            ExpertMark9 = 0.18793141697693216,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 66.241687632508231,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 25,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 8,
                            ExpertMark1 = 0.73465467700055465,
                            ExpertMark10 = 0.33064013076963172,
                            ExpertMark2 = 0.83857698953745863,
                            ExpertMark3 = 0.37807004821143342,
                            ExpertMark4 = 0.30979614247234355,
                            ExpertMark5 = 0.96552364200060348,
                            ExpertMark6 = 0.94463997183365322,
                            ExpertMark7 = 0.97524247480440562,
                            ExpertMark8 = 0.74300972895103612,
                            ExpertMark9 = 0.2984774304969452,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 67.184686480147093,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 26,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 9,
                            ExpertMark1 = 0.66780558916715027,
                            ExpertMark10 = 0.79550042683030642,
                            ExpertMark2 = 0.81748127250573854,
                            ExpertMark3 = 0.16777464038371814,
                            ExpertMark4 = 0.39806744827943474,
                            ExpertMark5 = 0.5608670514216656,
                            ExpertMark6 = 0.75484950438776388,
                            ExpertMark7 = 0.69896338223275267,
                            ExpertMark8 = 0.87515247912174443,
                            ExpertMark9 = 0.70151456882292651,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 81.568024732506387,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 27,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 10,
                            ExpertMark1 = 0.18585640740222575,
                            ExpertMark10 = 0.51282255047404945,
                            ExpertMark2 = 0.81906899115694065,
                            ExpertMark3 = 0.79558823450275296,
                            ExpertMark4 = 0.57605455619220536,
                            ExpertMark5 = 0.87546565176980085,
                            ExpertMark6 = 0.92822850923513656,
                            ExpertMark7 = 0.74826060792612215,
                            ExpertMark8 = 0.37154890260199014,
                            ExpertMark9 = 0.22443585809207989,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 58.59333646428211,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 28,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 11,
                            ExpertMark1 = 0.41212488338422315,
                            ExpertMark10 = 0.13907543979595349,
                            ExpertMark2 = 0.85044764578226784,
                            ExpertMark3 = 0.56119111404691313,
                            ExpertMark4 = 0.7965647071778087,
                            ExpertMark5 = 0.59621089014045714,
                            ExpertMark6 = 0.85417400758032525,
                            ExpertMark7 = 0.81168264723926808,
                            ExpertMark8 = 0.58648933463032193,
                            ExpertMark9 = 0.91921738610274184,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 57.67580119225719,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 29,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 12,
                            ExpertMark1 = 0.10721566662203252,
                            ExpertMark10 = 0.19046468145721418,
                            ExpertMark2 = 0.52147097185875735,
                            ExpertMark3 = 0.51996022069273462,
                            ExpertMark4 = 0.19192015748063918,
                            ExpertMark5 = 0.10042616874810895,
                            ExpertMark6 = 0.36631851867637366,
                            ExpertMark7 = 0.71993293511740375,
                            ExpertMark8 = 0.15077651402821801,
                            ExpertMark9 = 0.53007061766561037,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 17.949470100827657,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 30,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 13,
                            ExpertMark1 = 0.095609490907959782,
                            ExpertMark10 = 0.78752538200534272,
                            ExpertMark2 = 0.19461092817008641,
                            ExpertMark3 = 0.42966642998045734,
                            ExpertMark4 = 0.3996803118168204,
                            ExpertMark5 = 0.062456754414335069,
                            ExpertMark6 = 0.40978686997267677,
                            ExpertMark7 = 0.74136887898377068,
                            ExpertMark8 = 0.24354737935859061,
                            ExpertMark9 = 0.12824360263732137,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 76.981909251570286,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 31,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 14,
                            ExpertMark1 = 0.10511529645173046,
                            ExpertMark10 = 0.46122461358344591,
                            ExpertMark2 = 0.93564870095090513,
                            ExpertMark3 = 0.61539561033576506,
                            ExpertMark4 = 0.83302881042196353,
                            ExpertMark5 = 0.83818954523977729,
                            ExpertMark6 = 0.83279053073697118,
                            ExpertMark7 = 0.17765927932761905,
                            ExpertMark8 = 0.92968735416517423,
                            ExpertMark9 = 0.72857654111683157,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 68.686991843674477,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 32,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 15,
                            ExpertMark1 = 0.36800162568661465,
                            ExpertMark10 = 0.073483578273869532,
                            ExpertMark2 = 0.10773018337087004,
                            ExpertMark3 = 0.43106120169880568,
                            ExpertMark4 = 0.61563637098670076,
                            ExpertMark5 = 0.0207829403044969,
                            ExpertMark6 = 0.44933235011599304,
                            ExpertMark7 = 0.3869335058199983,
                            ExpertMark8 = 0.24313084092790638,
                            ExpertMark9 = 0.066094782014071041,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 8.9486218424054247,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 33,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 16,
                            ExpertMark1 = 0.86180214397000243,
                            ExpertMark10 = 0.73171402645856065,
                            ExpertMark2 = 0.56228234979269509,
                            ExpertMark3 = 0.39327050303534195,
                            ExpertMark4 = 0.088409088150666393,
                            ExpertMark5 = 0.6686673837150876,
                            ExpertMark6 = 0.077237316710673576,
                            ExpertMark7 = 0.5041771205124036,
                            ExpertMark8 = 0.36810931020910975,
                            ExpertMark9 = 0.27479643569671319,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 38.069523840025219,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 34,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 17,
                            ExpertMark1 = 0.77090008463907822,
                            ExpertMark10 = 0.82292724928057426,
                            ExpertMark2 = 0.097414405151026506,
                            ExpertMark3 = 0.72274498999014769,
                            ExpertMark4 = 0.25367675882686092,
                            ExpertMark5 = 0.91601661056573003,
                            ExpertMark6 = 0.61201576558687698,
                            ExpertMark7 = 0.91311607443335563,
                            ExpertMark8 = 0.54520180163613086,
                            ExpertMark9 = 0.092193309383000854,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 29.126535195648263,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 35,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 18,
                            ExpertMark1 = 0.70839220943032732,
                            ExpertMark10 = 0.85905245639957561,
                            ExpertMark2 = 0.83412714819811407,
                            ExpertMark3 = 0.054942631852356594,
                            ExpertMark4 = 0.0026391986650448063,
                            ExpertMark5 = 0.6401334309541229,
                            ExpertMark6 = 0.33136680729454537,
                            ExpertMark7 = 0.6169328008695889,
                            ExpertMark8 = 0.092331684308710638,
                            ExpertMark9 = 0.40312489695341891,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 85.549920622862516,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 36,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 19,
                            ExpertMark1 = 0.58328019228379546,
                            ExpertMark10 = 0.76444339190487043,
                            ExpertMark2 = 0.037701265256956495,
                            ExpertMark3 = 0.0050223752320338599,
                            ExpertMark4 = 0.10353347304329086,
                            ExpertMark5 = 0.36922494082308865,
                            ExpertMark6 = 0.89786536712129839,
                            ExpertMark7 = 0.047610790328670882,
                            ExpertMark8 = 0.75487979711415976,
                            ExpertMark9 = 0.40174045198462538,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 67.539398748540904,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 37,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 20,
                            ExpertMark1 = 0.75448935632046277,
                            ExpertMark10 = 0.03781765532435688,
                            ExpertMark2 = 0.42712546686861386,
                            ExpertMark3 = 0.032650452125110196,
                            ExpertMark4 = 0.32093136039761305,
                            ExpertMark5 = 0.8944196131869836,
                            ExpertMark6 = 0.35830531526379428,
                            ExpertMark7 = 0.71637783365970453,
                            ExpertMark8 = 0.80612227797493397,
                            ExpertMark9 = 0.3939002418031744,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 92.401133040062788,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 38,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 21,
                            ExpertMark1 = 0.9176266237645041,
                            ExpertMark10 = 0.70259170628687762,
                            ExpertMark2 = 0.31465367953048862,
                            ExpertMark3 = 0.77304368412127411,
                            ExpertMark4 = 0.80333185871442436,
                            ExpertMark5 = 0.60631562029083019,
                            ExpertMark6 = 0.46878314375896357,
                            ExpertMark7 = 0.82557342269680611,
                            ExpertMark8 = 0.21946568944220179,
                            ExpertMark9 = 0.87974988645284879,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 11.722548046339776,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 39,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 22,
                            ExpertMark1 = 0.036085376529065738,
                            ExpertMark10 = 0.99419795521584686,
                            ExpertMark2 = 0.13865700230264322,
                            ExpertMark3 = 0.013743057452528573,
                            ExpertMark4 = 0.90409083117227285,
                            ExpertMark5 = 0.68905265948733585,
                            ExpertMark6 = 0.56833545190245627,
                            ExpertMark7 = 0.099394685317817366,
                            ExpertMark8 = 0.13606169775087984,
                            ExpertMark9 = 0.63208251262060688,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 25.126673397661236,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 40,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 23,
                            ExpertMark1 = 0.29973097076084754,
                            ExpertMark10 = 0.036963830092384686,
                            ExpertMark2 = 0.662868522103088,
                            ExpertMark3 = 0.11466607938175577,
                            ExpertMark4 = 0.41703330577321063,
                            ExpertMark5 = 0.21799133956265582,
                            ExpertMark6 = 0.8326833193818749,
                            ExpertMark7 = 0.31340684795442875,
                            ExpertMark8 = 0.56785656940373874,
                            ExpertMark9 = 0.016024478704788292,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 3.283168111252599,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 41,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 24,
                            ExpertMark1 = 0.77584954160375896,
                            ExpertMark10 = 0.6071663490688749,
                            ExpertMark2 = 0.15788525522651631,
                            ExpertMark3 = 0.29014723804738074,
                            ExpertMark4 = 0.26830653351568146,
                            ExpertMark5 = 0.99878517641457476,
                            ExpertMark6 = 0.62207022159373038,
                            ExpertMark7 = 0.41057222526873072,
                            ExpertMark8 = 0.62186356598123349,
                            ExpertMark9 = 0.59189749229193866,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 86.817405588967588,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 42,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 25,
                            ExpertMark1 = 0.23679902705406464,
                            ExpertMark10 = 0.20110542117591579,
                            ExpertMark2 = 0.098325524902349914,
                            ExpertMark3 = 0.56589005654317481,
                            ExpertMark4 = 0.39642270551510872,
                            ExpertMark5 = 0.99777271936090173,
                            ExpertMark6 = 0.22723706433810886,
                            ExpertMark7 = 0.92939116080372541,
                            ExpertMark8 = 0.60593310638595654,
                            ExpertMark9 = 0.45548635201452159,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 67.310028893497503,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 43,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 26,
                            ExpertMark1 = 0.33129453363881567,
                            ExpertMark10 = 0.11446308962602514,
                            ExpertMark2 = 0.57221553296676497,
                            ExpertMark3 = 0.90794163586131582,
                            ExpertMark4 = 0.93810800842476427,
                            ExpertMark5 = 0.75757888308724897,
                            ExpertMark6 = 0.42716438586409522,
                            ExpertMark7 = 0.24076549378922141,
                            ExpertMark8 = 0.13570759211014305,
                            ExpertMark9 = 0.80933037617608672,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 26.646731520487489,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 44,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 27,
                            ExpertMark1 = 0.27655181904030013,
                            ExpertMark10 = 0.10008863124983669,
                            ExpertMark2 = 0.76420720228354855,
                            ExpertMark3 = 0.054674503363103755,
                            ExpertMark4 = 0.82318313854651759,
                            ExpertMark5 = 0.56111258646215278,
                            ExpertMark6 = 0.50396240102224399,
                            ExpertMark7 = 0.40244275812490837,
                            ExpertMark8 = 0.41207815584013407,
                            ExpertMark9 = 0.058893567421667514,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 52.503996569798652,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 45,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 28,
                            ExpertMark1 = 0.37616933517382589,
                            ExpertMark10 = 0.27154418729458418,
                            ExpertMark2 = 0.89240283393674591,
                            ExpertMark3 = 0.14858348815522959,
                            ExpertMark4 = 0.61220222469155783,
                            ExpertMark5 = 0.84499832209405457,
                            ExpertMark6 = 0.7765225537421514,
                            ExpertMark7 = 0.46438780339075136,
                            ExpertMark8 = 0.89138418553674081,
                            ExpertMark9 = 0.49569378928423768,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 65.736935336921533,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 46,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 29,
                            ExpertMark1 = 0.73340335663053846,
                            ExpertMark10 = 0.81254648588286293,
                            ExpertMark2 = 0.488437365917605,
                            ExpertMark3 = 0.79475290532028442,
                            ExpertMark4 = 0.75223102205445602,
                            ExpertMark5 = 0.87853925065497585,
                            ExpertMark6 = 0.49164203886732627,
                            ExpertMark7 = 0.17656110904483258,
                            ExpertMark8 = 0.63387165969655168,
                            ExpertMark9 = 0.34028942928763894,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 11.19949879621217,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 47,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 30,
                            ExpertMark1 = 0.2496982149714595,
                            ExpertMark10 = 0.97506312327192124,
                            ExpertMark2 = 0.87469343727226445,
                            ExpertMark3 = 0.9527166661358295,
                            ExpertMark4 = 0.69556388123508806,
                            ExpertMark5 = 0.0078202685209518563,
                            ExpertMark6 = 0.8051210507885872,
                            ExpertMark7 = 0.80524932586395137,
                            ExpertMark8 = 0.052998573628422196,
                            ExpertMark9 = 0.47151784093979132,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 2.119514042125592,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 48,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 31,
                            ExpertMark1 = 0.39818599163897672,
                            ExpertMark10 = 0.28044157038632589,
                            ExpertMark2 = 0.75615957842631765,
                            ExpertMark3 = 0.71534491354550789,
                            ExpertMark4 = 0.11678172205968052,
                            ExpertMark5 = 0.93636623176721145,
                            ExpertMark6 = 0.85487367343413234,
                            ExpertMark7 = 0.77199393080422862,
                            ExpertMark8 = 0.7736259045363495,
                            ExpertMark9 = 0.50922835181396708,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 21.695347476541627,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 49,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 32,
                            ExpertMark1 = 0.35961889553285908,
                            ExpertMark10 = 0.84002245232885231,
                            ExpertMark2 = 0.028198047439840113,
                            ExpertMark3 = 0.03685969501227826,
                            ExpertMark4 = 0.77149270817341919,
                            ExpertMark5 = 0.83129691928836758,
                            ExpertMark6 = 0.66972089535284296,
                            ExpertMark7 = 0.25514564045624233,
                            ExpertMark8 = 0.06811760376473619,
                            ExpertMark9 = 0.15296521504342231,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 93.663127757448024,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 50,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 33,
                            ExpertMark1 = 0.78748810317151519,
                            ExpertMark10 = 0.049526821130141507,
                            ExpertMark2 = 0.43696002014550528,
                            ExpertMark3 = 0.30534180402850375,
                            ExpertMark4 = 0.78956186921103322,
                            ExpertMark5 = 0.94738300106422091,
                            ExpertMark6 = 0.97486117377098014,
                            ExpertMark7 = 0.59138272501225031,
                            ExpertMark8 = 0.40424875497744772,
                            ExpertMark9 = 0.36696595797063958,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 79.545139219481982,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 51,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 34,
                            ExpertMark1 = 0.70570041059493016,
                            ExpertMark10 = 0.788151411545993,
                            ExpertMark2 = 0.82095112750088195,
                            ExpertMark3 = 0.17773426199733833,
                            ExpertMark4 = 0.96125755848661965,
                            ExpertMark5 = 0.95256059120352943,
                            ExpertMark6 = 0.96813445425480049,
                            ExpertMark7 = 0.94193165990637528,
                            ExpertMark8 = 0.050267666753448514,
                            ExpertMark9 = 0.48227521933717055,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 92.64336902234443,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 52,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 35,
                            ExpertMark1 = 0.21024604762449117,
                            ExpertMark10 = 0.86865124920570402,
                            ExpertMark2 = 0.68470104301972823,
                            ExpertMark3 = 0.73373571832144413,
                            ExpertMark4 = 0.50036693333333526,
                            ExpertMark5 = 0.48741133090397137,
                            ExpertMark6 = 0.16819813020521412,
                            ExpertMark7 = 0.013520782000434162,
                            ExpertMark8 = 0.62705434032915564,
                            ExpertMark9 = 0.45343562444066521,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 57.39443266832415,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 53,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 36,
                            ExpertMark1 = 0.15975150535857385,
                            ExpertMark10 = 0.86188344547504925,
                            ExpertMark2 = 0.53208245971554902,
                            ExpertMark3 = 0.59934988522442512,
                            ExpertMark4 = 0.04907792294120783,
                            ExpertMark5 = 0.49153268981148268,
                            ExpertMark6 = 0.42381775876714722,
                            ExpertMark7 = 0.08806263044641871,
                            ExpertMark8 = 0.5690047288785044,
                            ExpertMark9 = 0.76859864096233055,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 19.833348326691425,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 54,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 37,
                            ExpertMark1 = 0.77115906240524268,
                            ExpertMark10 = 0.0071164274967436825,
                            ExpertMark2 = 0.75375682848430903,
                            ExpertMark3 = 0.86750142091053872,
                            ExpertMark4 = 0.86003853304836253,
                            ExpertMark5 = 0.70185469891921648,
                            ExpertMark6 = 0.86958165148365629,
                            ExpertMark7 = 0.13847046690857223,
                            ExpertMark8 = 0.25372971537280709,
                            ExpertMark9 = 0.83394286937471884,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 49.842126802770892,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 55,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 38,
                            ExpertMark1 = 0.92937379007336951,
                            ExpertMark10 = 0.85970606823594686,
                            ExpertMark2 = 0.90734176110319742,
                            ExpertMark3 = 0.77092961988930708,
                            ExpertMark4 = 0.74067951069971349,
                            ExpertMark5 = 0.098220461252380376,
                            ExpertMark6 = 0.10564778255612306,
                            ExpertMark7 = 0.32000759495340447,
                            ExpertMark8 = 0.68262164051056695,
                            ExpertMark9 = 0.13146333287982737,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 42.380126151563978,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 56,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 39,
                            ExpertMark1 = 0.53880001320071003,
                            ExpertMark10 = 0.16907401372974751,
                            ExpertMark2 = 0.50479206223921758,
                            ExpertMark3 = 0.74577890085721643,
                            ExpertMark4 = 0.27008007695906744,
                            ExpertMark5 = 0.06807293842382478,
                            ExpertMark6 = 0.37011436236336426,
                            ExpertMark7 = 0.28108260032751942,
                            ExpertMark8 = 0.17159960792029916,
                            ExpertMark9 = 0.59396014227990701,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 48.034598961205852,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 57,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 40,
                            ExpertMark1 = 0.53680188970925713,
                            ExpertMark10 = 0.17598002320210748,
                            ExpertMark2 = 0.44637905408566758,
                            ExpertMark3 = 0.4000976751700156,
                            ExpertMark4 = 0.36361796660921597,
                            ExpertMark5 = 0.82964112964689696,
                            ExpertMark6 = 0.16479014983719753,
                            ExpertMark7 = 0.35078416377919552,
                            ExpertMark8 = 0.47636441288461551,
                            ExpertMark9 = 0.38749605384565711,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 66.265863583170201,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 58,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 41,
                            ExpertMark1 = 0.2396165078608935,
                            ExpertMark10 = 0.83726389721565941,
                            ExpertMark2 = 0.18261767458653377,
                            ExpertMark3 = 0.42694944812373448,
                            ExpertMark4 = 0.12490619539353687,
                            ExpertMark5 = 0.90927931394455908,
                            ExpertMark6 = 0.056108272301555129,
                            ExpertMark7 = 0.1379987819391898,
                            ExpertMark8 = 0.75957120817726131,
                            ExpertMark9 = 0.92703317879473313,
                            ExpertMarkWeighed1 = 0.0,
                            ExpertMarkWeighed10 = 0.0,
                            ExpertMarkWeighed2 = 0.0,
                            ExpertMarkWeighed3 = 0.0,
                            ExpertMarkWeighed4 = 0.0,
                            ExpertMarkWeighed5 = 0.0,
                            ExpertMarkWeighed6 = 0.0,
                            ExpertMarkWeighed7 = 0.0,
                            ExpertMarkWeighed8 = 0.0,
                            ExpertMarkWeighed9 = 0.0,
                            Price = 63.29487442860956,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 59,
                            Summary = 0.0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpertCoef1")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef10")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef2")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef3")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef4")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef5")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef6")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef7")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef8")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef9")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Summary")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskExpertMarksCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            Name = "Множина настання технічних ризикових подій",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            Name = "Множина настання вартісних ризикових подій",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            Name = "Множина настання планових ризикових подій",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Price = 0.0,
                            Summary = 0,
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.HasOne("AppRisks.Models.RiskCategory", "RiskCategory")
                        .WithMany("Risks")
                        .HasForeignKey("RiskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.HasOne("AppRisks.Models.RiskExpertMarksCategory", "RiskExpertMarksCategory")
                        .WithMany("RiskExpertMarksList")
                        .HasForeignKey("RiskExpertMarksCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppRisks.Models.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("RiskExpertMarksCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Navigation("RiskExpertMarksList");
                });
#pragma warning restore 612, 618
        }
    }
}
