// <auto-generated />
using AppRisks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppRisks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221118121133_ChangeModels")]
    partial class ChangeModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskCategoryId");

                    b.ToTable("Risks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Функціональні характеристики ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Характеристики якості ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Характеристики надійності ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Застосовність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Часова продуктивність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Супроводжуваність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Повторне використання компонент ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Обмеження сумарного бюджету на програмний продукт",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Недоступна вартість реалізації програмного проекту",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Низька ступінь реалізму при оцінюванні витрат на програмний проект",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "Властивості та можливості гнучкості внесення змін до планів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            Content = "Можливості порушення встановлених термінів реалізації етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            Content = "Низька ступінь реалізму при встановленні планів і етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Хибна стратегія реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "Неефективне планування проекту розроблення ПЗ",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Неякісне оцінювання програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 17,
                            Content = "Прогалини в документуванні етапів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 18,
                            Content = "Промахи в прогнозуванні результатів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 19,
                            Content = "Затримки у постачанні обладнання, необхідного для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "Затримки у постачанні інструментальних засобів, необхідних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Небажання команди виконавців використовувати інструментальні засоби для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Content = "Формування запитів на більш потужні інструментальні засоби розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "Відмова команди виконавців від CASE-засобів розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 24,
                            Content = "Неефективність програмного коду, згенерованого CASE-засобами розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 25,
                            Content = "Неможливість інтеграції CASE-засобів з іншими інструментальними засобами для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "Недостатня продуктивність баз(и) даних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 27,
                            Content = "Програмні компоненти, які використовують повторно в ПЗ, мають дефекти та обмежені функціональні можливості",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "Швидкість виявлення дефектів у програмному коді є нижчою від раніше запланованих термінів",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 29,
                            Content = "Поява дефектних системних компонент, які використовують для розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Content = "Недо(пере)оцінювання витрат на реалізацію програмного проекту (надмірно низька вартість)",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 31,
                            Content = "Фінансові ускладнення у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 32,
                            Content = "Фінансові ускладнення у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 33,
                            Content = "Змен(збіль)шення бюджету програмного проекта з ініціативи компанії-замовника ПЗ під час його реалізації",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            Content = "Висока вартість виконання повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 35,
                            Content = "Реорганізація структурних підрозділів у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 36,
                            Content = "Реорганізація команди виконавців у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 37,
                            Content = "Зміни графіка виконання робіт з боку замовника чи розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            Content = "Порушення графіка виконання робіт з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 39,
                            Content = "Потреба зміни користувацьких вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 40,
                            Content = "Потреба зміни функціональних вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 41,
                            Content = "Потреба виконання великої кількості повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 42,
                            Content = "Недо(пере)оцінювання тривалості етапів реалізації програмного проекту з боку компанії-замовника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 43,
                            Content = "Остаточний розмір ПЗ значно перевищує (менший від) заплановані(их) його характеристики",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 44,
                            Content = "Поява на ринку аналогічного ПЗ до виходу замовленого",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 45,
                            Content = "Поява на ринку більш конкурентоздатного ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 46,
                            Content = "Низький моральний стан персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 47,
                            Content = "Низька взаємодія між членами команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 48,
                            Content = "Пасивність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 49,
                            Content = "Недостатня компетентність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 50,
                            Content = "Незадоволеність замовника результатами етапів реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 51,
                            Content = "Недостатня кількість фахівців у команді виконавців ПЗ з необхідним професійним рівнем",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 52,
                            Content = "Хвороба провідного виконавця в найкритичніший момент розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 53,
                            Content = "Одночасна хвороба декількох виконавців підчас розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 54,
                            Content = "Неможливість організації необхідного навчання персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 55,
                            Content = "Зміна пріоритетів у процесі управління програмним проектом",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "Недо(пере)оцінювання необхідної кількості розробників (підрядників і субпідрядників) на етапах життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 57,
                            Content = "Недостатнє (надмірне) документування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 58,
                            Content = "Нереалістичне прогнозування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 59,
                            Content = "Недостатній професійний рівень представників від компанії-замовника ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Множина джерел появи технічних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Множина джерел появи вартісних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Множина джерел появи планових ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Множина джерел появи ризиків реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Множина настання технічних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Множина настання вартісних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Множина настання планових ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ExpertMark1")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark10")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark2")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark3")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark4")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark5")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark6")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark7")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark8")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark9")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RiskExpertMarksCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.Property<double>("Summary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RiskExpertMarksCategoryId");

                    b.HasIndex("RiskId");

                    b.ToTable("RiskExpertMarksEnumerable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertMark1 = 0.4339198076297649,
                            ExpertMark10 = 0.54410330993907108,
                            ExpertMark2 = 0.82497743074046959,
                            ExpertMark3 = 0.48958542247678194,
                            ExpertMark4 = 0.88810157490703023,
                            ExpertMark5 = 0.49708118332864437,
                            ExpertMark6 = 0.018390160739709782,
                            ExpertMark7 = 0.15098760039883352,
                            ExpertMark8 = 0.1593983159936051,
                            ExpertMark9 = 0.88345969069296459,
                            Price = 51.334260279095588,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 19,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 2,
                            ExpertMark1 = 0.82529792271120839,
                            ExpertMark10 = 0.95611826566698266,
                            ExpertMark2 = 0.7648491631024239,
                            ExpertMark3 = 0.68220406758949348,
                            ExpertMark4 = 0.94618530013734348,
                            ExpertMark5 = 0.15317555981009734,
                            ExpertMark6 = 0.3212623972437918,
                            ExpertMark7 = 0.88946633071002501,
                            ExpertMark8 = 0.34444460038351188,
                            ExpertMark9 = 0.87487986095461934,
                            Price = 10.548102661803259,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 20,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 3,
                            ExpertMark1 = 0.18657569362816795,
                            ExpertMark10 = 0.036325692667876441,
                            ExpertMark2 = 0.58456638555455676,
                            ExpertMark3 = 0.46195864286506738,
                            ExpertMark4 = 0.60323350665953657,
                            ExpertMark5 = 0.234480952025379,
                            ExpertMark6 = 0.60266391528763608,
                            ExpertMark7 = 0.39129509697462428,
                            ExpertMark8 = 0.62523943607872956,
                            ExpertMark9 = 0.7556244516898093,
                            Price = 79.445653398416397,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 21,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 4,
                            ExpertMark1 = 0.073091328171246639,
                            ExpertMark10 = 0.59267216810084666,
                            ExpertMark2 = 0.10350673066238203,
                            ExpertMark3 = 0.006645676633398323,
                            ExpertMark4 = 0.86043627573014381,
                            ExpertMark5 = 0.67563511081480332,
                            ExpertMark6 = 0.2771440730710637,
                            ExpertMark7 = 0.044490943757413803,
                            ExpertMark8 = 0.56466015780508083,
                            ExpertMark9 = 0.24298078019563085,
                            Price = 33.791020477906777,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 22,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 5,
                            ExpertMark1 = 0.988324572184758,
                            ExpertMark10 = 0.94641771354560889,
                            ExpertMark2 = 0.69971643299700159,
                            ExpertMark3 = 0.3252112079486158,
                            ExpertMark4 = 0.26381083708992759,
                            ExpertMark5 = 0.21695632266216236,
                            ExpertMark6 = 0.22939580108563318,
                            ExpertMark7 = 0.08224460983281312,
                            ExpertMark8 = 0.54896190130713651,
                            ExpertMark9 = 0.047678473257270593,
                            Price = 43.49013071544119,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 23,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 6,
                            ExpertMark1 = 0.88337548906547936,
                            ExpertMark10 = 0.22778149290991201,
                            ExpertMark2 = 0.59560732340029132,
                            ExpertMark3 = 0.98885072032879828,
                            ExpertMark4 = 0.00037936890421119696,
                            ExpertMark5 = 0.4475751347987561,
                            ExpertMark6 = 0.61844702642141658,
                            ExpertMark7 = 0.022272408197234417,
                            ExpertMark8 = 0.75853226239057003,
                            ExpertMark9 = 0.80911359471981636,
                            Price = 97.892272633983097,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 24,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 7,
                            ExpertMark1 = 0.37260483551930967,
                            ExpertMark10 = 0.93615776226086544,
                            ExpertMark2 = 0.016486231901501669,
                            ExpertMark3 = 0.84350074231936245,
                            ExpertMark4 = 0.67125182346588386,
                            ExpertMark5 = 0.1061048858580862,
                            ExpertMark6 = 0.76543217256793417,
                            ExpertMark7 = 0.22580190326705563,
                            ExpertMark8 = 0.27291104950156087,
                            ExpertMark9 = 0.77919552594267416,
                            Price = 69.974577941407674,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 25,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 8,
                            ExpertMark1 = 0.58382103722561773,
                            ExpertMark10 = 0.014578046877769757,
                            ExpertMark2 = 0.51953186490355618,
                            ExpertMark3 = 0.46769609329235406,
                            ExpertMark4 = 0.065895163910311028,
                            ExpertMark5 = 0.27527268125455862,
                            ExpertMark6 = 0.081986648419718922,
                            ExpertMark7 = 0.84657370177808777,
                            ExpertMark8 = 0.50567398761165583,
                            ExpertMark9 = 0.41835316504438136,
                            Price = 30.889888377376952,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 26,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 9,
                            ExpertMark1 = 0.80138691454788147,
                            ExpertMark10 = 0.31336320367319404,
                            ExpertMark2 = 0.77641125730562732,
                            ExpertMark3 = 0.73997622126522911,
                            ExpertMark4 = 0.42758095201169255,
                            ExpertMark5 = 0.8012343044892728,
                            ExpertMark6 = 0.1820571053740111,
                            ExpertMark7 = 0.29559112710044155,
                            ExpertMark8 = 0.1317221620954202,
                            ExpertMark9 = 0.76267810494039967,
                            Price = 95.253470889296949,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 27,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 10,
                            ExpertMark1 = 0.47958256853782388,
                            ExpertMark10 = 0.8238378334196198,
                            ExpertMark2 = 0.27653588478992241,
                            ExpertMark3 = 0.95402000256917918,
                            ExpertMark4 = 0.31710586599486446,
                            ExpertMark5 = 0.061870338293880889,
                            ExpertMark6 = 0.48995806439818457,
                            ExpertMark7 = 0.94934219443908074,
                            ExpertMark8 = 0.58531077167981072,
                            ExpertMark9 = 0.23137716905646621,
                            Price = 46.834492846719222,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 28,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 11,
                            ExpertMark1 = 0.57727895937179363,
                            ExpertMark10 = 0.47953254070486728,
                            ExpertMark2 = 0.57737183658141011,
                            ExpertMark3 = 0.41996665782904907,
                            ExpertMark4 = 0.61512958552507369,
                            ExpertMark5 = 0.90364887650023895,
                            ExpertMark6 = 0.32130236930096912,
                            ExpertMark7 = 0.02197019546836676,
                            ExpertMark8 = 0.11477568125533055,
                            ExpertMark9 = 0.65596769691344725,
                            Price = 41.191563376639174,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 29,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 12,
                            ExpertMark1 = 0.84838508417430503,
                            ExpertMark10 = 0.21348481637319272,
                            ExpertMark2 = 0.36828388918460453,
                            ExpertMark3 = 0.32267384073100391,
                            ExpertMark4 = 0.32788088806753957,
                            ExpertMark5 = 0.34656216286649166,
                            ExpertMark6 = 0.62993322392446882,
                            ExpertMark7 = 0.11003496014355985,
                            ExpertMark8 = 0.78403343691491678,
                            ExpertMark9 = 0.63721369773280634,
                            Price = 93.877369883125695,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 30,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 13,
                            ExpertMark1 = 0.96141901132156316,
                            ExpertMark10 = 0.70107523866669752,
                            ExpertMark2 = 0.21517616834274245,
                            ExpertMark3 = 0.4176553911453269,
                            ExpertMark4 = 0.37071019333746624,
                            ExpertMark5 = 0.79377222582734708,
                            ExpertMark6 = 0.52149118724811705,
                            ExpertMark7 = 0.83883224179358151,
                            ExpertMark8 = 0.11158064275467905,
                            ExpertMark9 = 0.39845386640915559,
                            Price = 24.274886328081013,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 31,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 14,
                            ExpertMark1 = 0.25720010934825921,
                            ExpertMark10 = 0.2163990280850463,
                            ExpertMark2 = 0.95268392950325731,
                            ExpertMark3 = 0.53080512432102744,
                            ExpertMark4 = 0.95296337691144495,
                            ExpertMark5 = 0.88261929038076115,
                            ExpertMark6 = 0.7672903304004981,
                            ExpertMark7 = 0.73247441275621994,
                            ExpertMark8 = 0.80385838053306446,
                            ExpertMark9 = 0.80669325219766763,
                            Price = 27.785446865282925,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 32,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 15,
                            ExpertMark1 = 0.43921621325099147,
                            ExpertMark10 = 0.56417728984702731,
                            ExpertMark2 = 0.45151526237155437,
                            ExpertMark3 = 0.67082575101348807,
                            ExpertMark4 = 0.84278758488058914,
                            ExpertMark5 = 0.98456950835638202,
                            ExpertMark6 = 0.95103167280090228,
                            ExpertMark7 = 0.60838795029370651,
                            ExpertMark8 = 0.97099104730024843,
                            ExpertMark9 = 0.68511549552069706,
                            Price = 18.219197903496408,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 33,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 16,
                            ExpertMark1 = 0.081486723449303189,
                            ExpertMark10 = 0.012863283431060468,
                            ExpertMark2 = 0.19851049885780503,
                            ExpertMark3 = 0.51341959546807114,
                            ExpertMark4 = 0.39432727856378036,
                            ExpertMark5 = 0.97366632104794748,
                            ExpertMark6 = 0.37275554420872103,
                            ExpertMark7 = 0.49437722941588835,
                            ExpertMark8 = 0.13614604493980098,
                            ExpertMark9 = 0.017281578465556557,
                            Price = 25.548514790895428,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 34,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 17,
                            ExpertMark1 = 0.75005287515354413,
                            ExpertMark10 = 0.38913845156638438,
                            ExpertMark2 = 0.079965662850165709,
                            ExpertMark3 = 0.62212091871470199,
                            ExpertMark4 = 0.043987962328759012,
                            ExpertMark5 = 0.99388171948131443,
                            ExpertMark6 = 0.80697964953200019,
                            ExpertMark7 = 0.86497945381866093,
                            ExpertMark8 = 0.65905264579648237,
                            ExpertMark9 = 0.41959258779732778,
                            Price = 76.37236638488227,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 35,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 18,
                            ExpertMark1 = 0.40221355948804915,
                            ExpertMark10 = 0.33288049741765047,
                            ExpertMark2 = 0.45783184759009776,
                            ExpertMark3 = 0.49363976780781005,
                            ExpertMark4 = 0.57717316426789,
                            ExpertMark5 = 0.25792720804011404,
                            ExpertMark6 = 0.64440288531290346,
                            ExpertMark7 = 0.80683420217965818,
                            ExpertMark8 = 0.34655643751188769,
                            ExpertMark9 = 0.75165790759719542,
                            Price = 77.438319073444163,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 36,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 19,
                            ExpertMark1 = 0.27798916554987219,
                            ExpertMark10 = 0.80127560091579353,
                            ExpertMark2 = 0.65640190340636684,
                            ExpertMark3 = 0.18636810543726801,
                            ExpertMark4 = 0.41636925248623113,
                            ExpertMark5 = 0.176023060735229,
                            ExpertMark6 = 0.60613896712419357,
                            ExpertMark7 = 0.84892731107206565,
                            ExpertMark8 = 0.44303474322052716,
                            ExpertMark9 = 0.91717826791909141,
                            Price = 18.428789671824465,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 37,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 20,
                            ExpertMark1 = 0.36533762816058912,
                            ExpertMark10 = 0.32195223027285291,
                            ExpertMark2 = 0.19147752743224189,
                            ExpertMark3 = 0.28591660151851794,
                            ExpertMark4 = 0.52376122367978639,
                            ExpertMark5 = 0.27460787106416329,
                            ExpertMark6 = 0.896077503493656,
                            ExpertMark7 = 0.8133082386691658,
                            ExpertMark8 = 0.75257165241547042,
                            ExpertMark9 = 0.3341249223277144,
                            Price = 15.435878368470558,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 38,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 21,
                            ExpertMark1 = 0.97227235117969513,
                            ExpertMark10 = 0.76641225257067658,
                            ExpertMark2 = 0.98984084630816671,
                            ExpertMark3 = 0.6299124171870617,
                            ExpertMark4 = 0.8800377797535559,
                            ExpertMark5 = 0.81466995492728655,
                            ExpertMark6 = 0.00060973667213837235,
                            ExpertMark7 = 0.61350319959375099,
                            ExpertMark8 = 0.86744261015123081,
                            ExpertMark9 = 0.014275301687914799,
                            Price = 90.510270157678377,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 39,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 22,
                            ExpertMark1 = 0.59914330864917209,
                            ExpertMark10 = 0.46460499178414905,
                            ExpertMark2 = 0.96876243949309448,
                            ExpertMark3 = 0.88001428049866592,
                            ExpertMark4 = 0.35333507143830312,
                            ExpertMark5 = 0.24529394202104049,
                            ExpertMark6 = 0.47016832971427969,
                            ExpertMark7 = 0.50305524897010467,
                            ExpertMark8 = 0.32516789952027836,
                            ExpertMark9 = 0.89002203806229696,
                            Price = 93.586288281635504,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 40,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 23,
                            ExpertMark1 = 0.19596189461264746,
                            ExpertMark10 = 0.50378263243251897,
                            ExpertMark2 = 0.96772210636347222,
                            ExpertMark3 = 0.12488009912166176,
                            ExpertMark4 = 0.31578672649357931,
                            ExpertMark5 = 0.042499930758222559,
                            ExpertMark6 = 0.81648018437528624,
                            ExpertMark7 = 0.17987401896875521,
                            ExpertMark8 = 0.14273765586183329,
                            ExpertMark9 = 0.52836448790266888,
                            Price = 84.891999843727604,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 41,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 24,
                            ExpertMark1 = 0.55397809497489059,
                            ExpertMark10 = 0.53543535133451714,
                            ExpertMark2 = 0.4624656077693915,
                            ExpertMark3 = 0.55995945678123304,
                            ExpertMark4 = 0.24880228669606996,
                            ExpertMark5 = 0.21597413274435895,
                            ExpertMark6 = 0.41025696996116945,
                            ExpertMark7 = 0.60139971941209747,
                            ExpertMark8 = 0.48389698291745331,
                            ExpertMark9 = 0.18684432842466703,
                            Price = 94.875111945086232,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 42,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 25,
                            ExpertMark1 = 0.99322174231336224,
                            ExpertMark10 = 0.027836852133759749,
                            ExpertMark2 = 0.26955616800350468,
                            ExpertMark3 = 0.8670299892776937,
                            ExpertMark4 = 0.53550071985236858,
                            ExpertMark5 = 0.35946699629671308,
                            ExpertMark6 = 0.75406673198248997,
                            ExpertMark7 = 0.24143046607788365,
                            ExpertMark8 = 0.27195556573570046,
                            ExpertMark9 = 0.41569256059678072,
                            Price = 87.731440352228702,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 43,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 26,
                            ExpertMark1 = 0.60643862161170581,
                            ExpertMark10 = 0.62061199199394101,
                            ExpertMark2 = 0.57671936626383447,
                            ExpertMark3 = 0.74424115517839584,
                            ExpertMark4 = 0.69841941735486457,
                            ExpertMark5 = 0.13323918562622394,
                            ExpertMark6 = 0.38516702423981553,
                            ExpertMark7 = 0.80226764611238333,
                            ExpertMark8 = 0.5473213000992635,
                            ExpertMark9 = 0.37945451270817365,
                            Price = 60.404677515927695,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 44,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 27,
                            ExpertMark1 = 0.3265168722114633,
                            ExpertMark10 = 0.72950296030957695,
                            ExpertMark2 = 0.27523936384606995,
                            ExpertMark3 = 0.83147831181886855,
                            ExpertMark4 = 0.4297007239259576,
                            ExpertMark5 = 0.52453782640764024,
                            ExpertMark6 = 0.67721910649208394,
                            ExpertMark7 = 0.046935526941169758,
                            ExpertMark8 = 0.59246297547369786,
                            ExpertMark9 = 0.83105490404435967,
                            Price = 80.784769485328496,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 45,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 28,
                            ExpertMark1 = 0.072123204192030332,
                            ExpertMark10 = 0.22025186596785418,
                            ExpertMark2 = 0.038839652454314866,
                            ExpertMark3 = 0.78835760020434331,
                            ExpertMark4 = 0.42733555435986303,
                            ExpertMark5 = 0.96704154342213811,
                            ExpertMark6 = 0.90247541186005198,
                            ExpertMark7 = 0.95136835699708722,
                            ExpertMark8 = 0.34186048802154667,
                            ExpertMark9 = 0.15859541068487881,
                            Price = 13.811802330442035,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 46,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 29,
                            ExpertMark1 = 0.18802042146382736,
                            ExpertMark10 = 0.062413001610537311,
                            ExpertMark2 = 0.78409497445771181,
                            ExpertMark3 = 0.06452176979366353,
                            ExpertMark4 = 0.36468852369149118,
                            ExpertMark5 = 0.062914142429006614,
                            ExpertMark6 = 0.11599899941240432,
                            ExpertMark7 = 0.91548597714757463,
                            ExpertMark8 = 0.95127213781854059,
                            ExpertMark9 = 0.94725799697181845,
                            Price = 95.175343981086229,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 47,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 30,
                            ExpertMark1 = 0.78960201369170524,
                            ExpertMark10 = 0.46682351978481951,
                            ExpertMark2 = 0.77637298827864343,
                            ExpertMark3 = 0.89562295077417942,
                            ExpertMark4 = 0.31253524254443943,
                            ExpertMark5 = 0.70193658010385418,
                            ExpertMark6 = 0.10478141782939243,
                            ExpertMark7 = 0.70838335486736226,
                            ExpertMark8 = 0.52111139356364355,
                            ExpertMark9 = 0.20724946425611934,
                            Price = 22.24241902147449,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 48,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 31,
                            ExpertMark1 = 0.28984772061829522,
                            ExpertMark10 = 0.49943330472996028,
                            ExpertMark2 = 0.73558669064084936,
                            ExpertMark3 = 0.84225530799556103,
                            ExpertMark4 = 0.7426197533001736,
                            ExpertMark5 = 0.55936376185743286,
                            ExpertMark6 = 0.34240937899821122,
                            ExpertMark7 = 0.88812528835734506,
                            ExpertMark8 = 0.70638738081504737,
                            ExpertMark9 = 0.89296103220758904,
                            Price = 52.625026971708131,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 49,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 32,
                            ExpertMark1 = 0.79793104377637802,
                            ExpertMark10 = 0.020991484687175266,
                            ExpertMark2 = 0.3579311477705942,
                            ExpertMark3 = 0.97184928990528141,
                            ExpertMark4 = 0.82980164883477159,
                            ExpertMark5 = 0.84407015825427756,
                            ExpertMark6 = 0.45821565111412987,
                            ExpertMark7 = 0.047956271404946405,
                            ExpertMark8 = 0.67280377279103254,
                            ExpertMark9 = 0.95235187889161688,
                            Price = 23.245541984318187,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 50,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 33,
                            ExpertMark1 = 0.27930772172134521,
                            ExpertMark10 = 0.44411398827135662,
                            ExpertMark2 = 0.94334076366122532,
                            ExpertMark3 = 0.96799421785408291,
                            ExpertMark4 = 0.73656590056045212,
                            ExpertMark5 = 0.27546845118783203,
                            ExpertMark6 = 0.38187190875596277,
                            ExpertMark7 = 0.71491016367536309,
                            ExpertMark8 = 0.56317803101742103,
                            ExpertMark9 = 0.69031879158766607,
                            Price = 66.441602557536896,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 51,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 34,
                            ExpertMark1 = 0.9590438418467665,
                            ExpertMark10 = 0.23910834032222927,
                            ExpertMark2 = 0.77702952977329476,
                            ExpertMark3 = 0.040791007304743054,
                            ExpertMark4 = 0.61233301521395034,
                            ExpertMark5 = 0.031940794794243277,
                            ExpertMark6 = 0.2134354877575112,
                            ExpertMark7 = 0.54185195159731603,
                            ExpertMark8 = 0.6378252490113836,
                            ExpertMark9 = 0.58370952956427946,
                            Price = 96.897877026093965,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 52,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 35,
                            ExpertMark1 = 0.04836746847157547,
                            ExpertMark10 = 0.025052338905329874,
                            ExpertMark2 = 0.71398882350942094,
                            ExpertMark3 = 0.33129209041283381,
                            ExpertMark4 = 0.89210352421558581,
                            ExpertMark5 = 0.87347849172433467,
                            ExpertMark6 = 0.80465271872629929,
                            ExpertMark7 = 0.86007618503928418,
                            ExpertMark8 = 0.38325472253978254,
                            ExpertMark9 = 0.50427003898516465,
                            Price = 63.025443058900109,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 53,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 36,
                            ExpertMark1 = 0.10731301499641044,
                            ExpertMark10 = 0.035125466726869892,
                            ExpertMark2 = 0.226681027882085,
                            ExpertMark3 = 0.7159852711776924,
                            ExpertMark4 = 0.046847725210754421,
                            ExpertMark5 = 0.96010492562100214,
                            ExpertMark6 = 0.90479206026143721,
                            ExpertMark7 = 0.25023185983712526,
                            ExpertMark8 = 0.67114525701028283,
                            ExpertMark9 = 0.51106939223540127,
                            Price = 95.73576475018433,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 54,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 37,
                            ExpertMark1 = 0.56017801985367799,
                            ExpertMark10 = 0.30019797857152952,
                            ExpertMark2 = 0.70493883700385696,
                            ExpertMark3 = 0.85708660778001655,
                            ExpertMark4 = 0.64907534666948918,
                            ExpertMark5 = 0.99950173033400935,
                            ExpertMark6 = 0.45861561107675131,
                            ExpertMark7 = 0.55688292739833367,
                            ExpertMark8 = 0.17442059002367827,
                            ExpertMark9 = 0.89806822156150878,
                            Price = 72.446484648242944,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 55,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 38,
                            ExpertMark1 = 0.30930153791470305,
                            ExpertMark10 = 0.4517330728881791,
                            ExpertMark2 = 0.66116214977915877,
                            ExpertMark3 = 0.98487842422701921,
                            ExpertMark4 = 0.98106133029368692,
                            ExpertMark5 = 0.73436454644621063,
                            ExpertMark6 = 0.85014560560373109,
                            ExpertMark7 = 0.91290748661887666,
                            ExpertMark8 = 0.51397093258716919,
                            ExpertMark9 = 0.49050766765169751,
                            Price = 55.834853788710859,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 56,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 39,
                            ExpertMark1 = 0.84365573600549559,
                            ExpertMark10 = 0.13516255487417117,
                            ExpertMark2 = 0.60130197170332511,
                            ExpertMark3 = 0.73524749485868912,
                            ExpertMark4 = 0.90616656654373107,
                            ExpertMark5 = 0.6568054296659549,
                            ExpertMark6 = 0.93012787243748118,
                            ExpertMark7 = 0.088606570040584809,
                            ExpertMark8 = 0.19383281935641261,
                            ExpertMark9 = 0.64004010285748869,
                            Price = 63.486768945880378,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 57,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 40,
                            ExpertMark1 = 0.87809592848661167,
                            ExpertMark10 = 0.36732300310565069,
                            ExpertMark2 = 0.41813677368519486,
                            ExpertMark3 = 0.2822909909137864,
                            ExpertMark4 = 0.80204483655984871,
                            ExpertMark5 = 0.15699103226686262,
                            ExpertMark6 = 0.5596064793841552,
                            ExpertMark7 = 0.049259070301649555,
                            ExpertMark8 = 0.87367295031813486,
                            ExpertMark9 = 0.38444279837918938,
                            Price = 97.991917953898778,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 58,
                            Summary = 0.0
                        },
                        new
                        {
                            Id = 41,
                            ExpertMark1 = 0.47017017074930856,
                            ExpertMark10 = 0.56936700898095238,
                            ExpertMark2 = 0.044864731218208331,
                            ExpertMark3 = 0.17162737700787056,
                            ExpertMark4 = 0.49790182773681757,
                            ExpertMark5 = 0.3132106000718704,
                            ExpertMark6 = 0.51840912161130093,
                            ExpertMark7 = 0.21804240740268532,
                            ExpertMark8 = 0.91930879870689541,
                            ExpertMark9 = 0.97673508387936081,
                            Price = 87.951001858838779,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 59,
                            Summary = 0.0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpertCoef1")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef10")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef2")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef3")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef4")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef5")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef6")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef7")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef8")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef9")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskExpertMarksCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            Name = "Множина настання технічних ризикових подій",
                            Price = 0.0,
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            Name = "Множина настання вартісних ризикових подій",
                            Price = 0.0,
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            Name = "Множина настання планових ризикових подій",
                            Price = 0.0,
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Price = 0.0,
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.HasOne("AppRisks.Models.RiskCategory", "RiskCategory")
                        .WithMany("Risks")
                        .HasForeignKey("RiskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.HasOne("AppRisks.Models.RiskExpertMarksCategory", "RiskExpertMarksCategory")
                        .WithMany("RiskExpertMarksList")
                        .HasForeignKey("RiskExpertMarksCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppRisks.Models.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("RiskExpertMarksCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Navigation("RiskExpertMarksList");
                });
#pragma warning restore 612, 618
        }
    }
}
