// <auto-generated />
using AppRisks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppRisks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221118113836_MoveExpertCoef")]
    partial class MoveExpertCoef
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskCategoryId");

                    b.ToTable("Risks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Функціональні характеристики ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Характеристики якості ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Характеристики надійності ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Застосовність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Часова продуктивність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Супроводжуваність ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Повторне використання компонент ПЗ",
                            RiskCategoryId = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Обмеження сумарного бюджету на програмний продукт",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Недоступна вартість реалізації програмного проекту",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Низька ступінь реалізму при оцінюванні витрат на програмний проект",
                            RiskCategoryId = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "Властивості та можливості гнучкості внесення змін до планів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 12,
                            Content = "Можливості порушення встановлених термінів реалізації етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 13,
                            Content = "Низька ступінь реалізму при встановленні планів і етапів життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 3,
                            Value = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Хибна стратегія реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "Неефективне планування проекту розроблення ПЗ",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Неякісне оцінювання програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 17,
                            Content = "Прогалини в документуванні етапів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 18,
                            Content = "Промахи в прогнозуванні результатів реалізації програмного проекту",
                            RiskCategoryId = 4,
                            Value = 1
                        },
                        new
                        {
                            Id = 19,
                            Content = "Затримки у постачанні обладнання, необхідного для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "Затримки у постачанні інструментальних засобів, необхідних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 21,
                            Content = "Небажання команди виконавців використовувати інструментальні засоби для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 22,
                            Content = "Формування запитів на більш потужні інструментальні засоби розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "Відмова команди виконавців від CASE-засобів розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 24,
                            Content = "Неефективність програмного коду, згенерованого CASE-засобами розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 25,
                            Content = "Неможливість інтеграції CASE-засобів з іншими інструментальними засобами для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "Недостатня продуктивність баз(и) даних для підтримки процесу розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 27,
                            Content = "Програмні компоненти, які використовують повторно в ПЗ, мають дефекти та обмежені функціональні можливості",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "Швидкість виявлення дефектів у програмному коді є нижчою від раніше запланованих термінів",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 29,
                            Content = "Поява дефектних системних компонент, які використовують для розроблення ПЗ",
                            RiskCategoryId = 5,
                            Value = 1
                        },
                        new
                        {
                            Id = 30,
                            Content = "Недо(пере)оцінювання витрат на реалізацію програмного проекту (надмірно низька вартість)",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 31,
                            Content = "Фінансові ускладнення у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 32,
                            Content = "Фінансові ускладнення у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 33,
                            Content = "Змен(збіль)шення бюджету програмного проекта з ініціативи компанії-замовника ПЗ під час його реалізації",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 34,
                            Content = "Висока вартість виконання повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 35,
                            Content = "Реорганізація структурних підрозділів у компанії-замовника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 36,
                            Content = "Реорганізація команди виконавців у компанії-розробника ПЗ",
                            RiskCategoryId = 6,
                            Value = 1
                        },
                        new
                        {
                            Id = 37,
                            Content = "Зміни графіка виконання робіт з боку замовника чи розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 38,
                            Content = "Порушення графіка виконання робіт з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 39,
                            Content = "Потреба зміни користувацьких вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 40,
                            Content = "Потреба зміни функціональних вимог до ПЗ з боку компанії-розробника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 41,
                            Content = "Потреба виконання великої кількості повторних робіт, необхідних для зміни вимог до ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 42,
                            Content = "Недо(пере)оцінювання тривалості етапів реалізації програмного проекту з боку компанії-замовника ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 43,
                            Content = "Остаточний розмір ПЗ значно перевищує (менший від) заплановані(их) його характеристики",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 44,
                            Content = "Поява на ринку аналогічного ПЗ до виходу замовленого",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 45,
                            Content = "Поява на ринку більш конкурентоздатного ПЗ",
                            RiskCategoryId = 7,
                            Value = 1
                        },
                        new
                        {
                            Id = 46,
                            Content = "Низький моральний стан персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 47,
                            Content = "Низька взаємодія між членами команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 48,
                            Content = "Пасивність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 49,
                            Content = "Недостатня компетентність керівника (менеджера) програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 50,
                            Content = "Незадоволеність замовника результатами етапів реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 51,
                            Content = "Недостатня кількість фахівців у команді виконавців ПЗ з необхідним професійним рівнем",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 52,
                            Content = "Хвороба провідного виконавця в найкритичніший момент розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 53,
                            Content = "Одночасна хвороба декількох виконавців підчас розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 54,
                            Content = "Неможливість організації необхідного навчання персоналу команди виконавців ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 55,
                            Content = "Зміна пріоритетів у процесі управління програмним проектом",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "Недо(пере)оцінювання необхідної кількості розробників (підрядників і субпідрядників) на етапах життєвого циклу розроблення ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 57,
                            Content = "Недостатнє (надмірне) документування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 58,
                            Content = "Нереалістичне прогнозування результатів на етапах реалізації програмного проекту",
                            RiskCategoryId = 8,
                            Value = 1
                        },
                        new
                        {
                            Id = 59,
                            Content = "Недостатній професійний рівень представників від компанії-замовника ПЗ",
                            RiskCategoryId = 8,
                            Value = 1
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Множина джерел появи технічних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Множина джерел появи вартісних ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Множина джерел появи планових ризиків",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Множина джерел появи ризиків реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Визначення можливих джерел появи ризиків",
                            Value = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Множина настання технічних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Множина настання вартісних ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Множина настання планових ризикових подій",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом",
                            Percentage = 0.0,
                            Section = "Ідентифікація потенційних ризикових подій",
                            Value = 0
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ExpertMark1")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark10")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark2")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark3")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark4")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark5")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark6")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark7")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark8")
                        .HasColumnType("float");

                    b.Property<double>("ExpertMark9")
                        .HasColumnType("float");

                    b.Property<int>("RiskExpertMarksCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskExpertMarksCategoryId");

                    b.HasIndex("RiskId");

                    b.ToTable("RiskExpertMarksEnumerable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertMark1 = 0.70411581986488148,
                            ExpertMark10 = 0.34350088069905393,
                            ExpertMark2 = 0.76364562763407406,
                            ExpertMark3 = 0.79478205686280179,
                            ExpertMark4 = 0.33500653612383136,
                            ExpertMark5 = 0.2942067910597308,
                            ExpertMark6 = 0.84630236837810535,
                            ExpertMark7 = 0.78997261748842373,
                            ExpertMark8 = 0.22995995048857676,
                            ExpertMark9 = 0.52485056726401835,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 19
                        },
                        new
                        {
                            Id = 2,
                            ExpertMark1 = 0.31913413981225414,
                            ExpertMark10 = 0.25187426352232167,
                            ExpertMark2 = 0.87581384123599981,
                            ExpertMark3 = 0.6050023242656688,
                            ExpertMark4 = 0.64728466082997937,
                            ExpertMark5 = 0.88921015621372634,
                            ExpertMark6 = 0.023808038646576102,
                            ExpertMark7 = 0.6392991899263768,
                            ExpertMark8 = 0.21610501545257221,
                            ExpertMark9 = 0.63525602875412635,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 20
                        },
                        new
                        {
                            Id = 3,
                            ExpertMark1 = 0.16220820082523602,
                            ExpertMark10 = 0.75739859206891158,
                            ExpertMark2 = 0.6038879663198129,
                            ExpertMark3 = 0.6932748336324982,
                            ExpertMark4 = 0.31383520281690813,
                            ExpertMark5 = 0.5831353936431708,
                            ExpertMark6 = 0.027769101587805878,
                            ExpertMark7 = 0.23615243300123601,
                            ExpertMark8 = 0.41564410199860402,
                            ExpertMark9 = 0.3722474945788673,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 21
                        },
                        new
                        {
                            Id = 4,
                            ExpertMark1 = 0.24692968205050647,
                            ExpertMark10 = 0.23233829703637354,
                            ExpertMark2 = 0.62729832722313206,
                            ExpertMark3 = 0.28179315314047937,
                            ExpertMark4 = 0.24824909637880155,
                            ExpertMark5 = 0.96378926528642128,
                            ExpertMark6 = 0.51920323093997001,
                            ExpertMark7 = 0.2018350672283481,
                            ExpertMark8 = 0.54636133926459995,
                            ExpertMark9 = 0.93216924587177996,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 22
                        },
                        new
                        {
                            Id = 5,
                            ExpertMark1 = 0.33288746830815052,
                            ExpertMark10 = 0.62751513149853888,
                            ExpertMark2 = 0.70525082217391977,
                            ExpertMark3 = 0.068679844636105547,
                            ExpertMark4 = 0.49036394965225738,
                            ExpertMark5 = 0.013861783459889976,
                            ExpertMark6 = 0.71641235527089087,
                            ExpertMark7 = 0.43931874154022588,
                            ExpertMark8 = 0.94523522014631134,
                            ExpertMark9 = 0.12833167744626195,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 23
                        },
                        new
                        {
                            Id = 6,
                            ExpertMark1 = 0.53073612866702469,
                            ExpertMark10 = 0.51835729551871812,
                            ExpertMark2 = 0.93882246369393518,
                            ExpertMark3 = 0.55555827083129072,
                            ExpertMark4 = 0.12946559771940369,
                            ExpertMark5 = 0.12770017689147339,
                            ExpertMark6 = 0.86666133143215263,
                            ExpertMark7 = 0.8575075238440365,
                            ExpertMark8 = 0.51303395235189941,
                            ExpertMark9 = 0.67663314858075752,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 24
                        },
                        new
                        {
                            Id = 7,
                            ExpertMark1 = 0.94151035439405106,
                            ExpertMark10 = 0.10251840698379666,
                            ExpertMark2 = 0.1544861593562139,
                            ExpertMark3 = 0.039964651667061424,
                            ExpertMark4 = 0.61552234240769743,
                            ExpertMark5 = 0.75630255208806529,
                            ExpertMark6 = 0.13715573238496059,
                            ExpertMark7 = 0.47457298117527791,
                            ExpertMark8 = 0.62307434869694067,
                            ExpertMark9 = 0.08614361165697737,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 25
                        },
                        new
                        {
                            Id = 8,
                            ExpertMark1 = 0.92984638117607454,
                            ExpertMark10 = 0.45881363910971029,
                            ExpertMark2 = 0.85845835961701344,
                            ExpertMark3 = 0.93372827837634298,
                            ExpertMark4 = 0.87627734424105119,
                            ExpertMark5 = 0.11491733745704513,
                            ExpertMark6 = 0.85747708486080454,
                            ExpertMark7 = 0.69259482895555091,
                            ExpertMark8 = 0.8594508046472642,
                            ExpertMark9 = 0.81958578523692416,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 26
                        },
                        new
                        {
                            Id = 9,
                            ExpertMark1 = 0.61351356978973748,
                            ExpertMark10 = 0.46638301123557169,
                            ExpertMark2 = 0.02098348510095227,
                            ExpertMark3 = 0.73319045211081968,
                            ExpertMark4 = 0.51698679176324103,
                            ExpertMark5 = 0.45829532149465269,
                            ExpertMark6 = 0.93697070104873414,
                            ExpertMark7 = 0.56769454938844088,
                            ExpertMark8 = 0.98130456431680291,
                            ExpertMark9 = 0.35854011078097081,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 27
                        },
                        new
                        {
                            Id = 10,
                            ExpertMark1 = 0.48849826343348701,
                            ExpertMark10 = 0.48865985606852547,
                            ExpertMark2 = 0.27637891341941234,
                            ExpertMark3 = 0.93782893784956867,
                            ExpertMark4 = 0.84429980552189088,
                            ExpertMark5 = 0.78285337780387509,
                            ExpertMark6 = 0.51937336166098036,
                            ExpertMark7 = 0.93626971616076016,
                            ExpertMark8 = 0.96700532122048644,
                            ExpertMark9 = 0.95923256008906599,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 28
                        },
                        new
                        {
                            Id = 11,
                            ExpertMark1 = 0.050513677952254143,
                            ExpertMark10 = 0.29750995539536196,
                            ExpertMark2 = 0.47090453105803254,
                            ExpertMark3 = 0.21443782109269149,
                            ExpertMark4 = 0.011394183933417845,
                            ExpertMark5 = 0.38729846707745441,
                            ExpertMark6 = 0.041352648780340284,
                            ExpertMark7 = 0.30527001958589117,
                            ExpertMark8 = 0.16473769869841093,
                            ExpertMark9 = 0.93867018640878463,
                            RiskExpertMarksCategoryId = 1,
                            RiskId = 29
                        },
                        new
                        {
                            Id = 12,
                            ExpertMark1 = 0.83781585565080841,
                            ExpertMark10 = 0.8597833746307546,
                            ExpertMark2 = 0.33638236139700051,
                            ExpertMark3 = 0.51065506621293044,
                            ExpertMark4 = 0.39984593356712317,
                            ExpertMark5 = 0.59975879971829482,
                            ExpertMark6 = 0.63850333984057328,
                            ExpertMark7 = 0.8837168397188464,
                            ExpertMark8 = 0.62500323818453363,
                            ExpertMark9 = 0.78979457430611,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 30
                        },
                        new
                        {
                            Id = 13,
                            ExpertMark1 = 0.92993187493170082,
                            ExpertMark10 = 0.50547084648126295,
                            ExpertMark2 = 0.48404098569745013,
                            ExpertMark3 = 0.50924041635933759,
                            ExpertMark4 = 0.59011274102422406,
                            ExpertMark5 = 0.1957651947599276,
                            ExpertMark6 = 0.77652368881216682,
                            ExpertMark7 = 0.28096211331885856,
                            ExpertMark8 = 0.94749081453522133,
                            ExpertMark9 = 0.46621995332029287,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 31
                        },
                        new
                        {
                            Id = 14,
                            ExpertMark1 = 0.76635194074028767,
                            ExpertMark10 = 0.88970472498892261,
                            ExpertMark2 = 0.99846529285333574,
                            ExpertMark3 = 0.035444065592401208,
                            ExpertMark4 = 0.5418933191416041,
                            ExpertMark5 = 0.92800774063185798,
                            ExpertMark6 = 0.45584096806941032,
                            ExpertMark7 = 0.32678052212386555,
                            ExpertMark8 = 0.87512825697454966,
                            ExpertMark9 = 0.76186627393653206,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 32
                        },
                        new
                        {
                            Id = 15,
                            ExpertMark1 = 0.79400536488098139,
                            ExpertMark10 = 0.59204564238874835,
                            ExpertMark2 = 0.93598694617786249,
                            ExpertMark3 = 0.33989781994200152,
                            ExpertMark4 = 0.32066255091008389,
                            ExpertMark5 = 0.18606235458291454,
                            ExpertMark6 = 0.91713199239493526,
                            ExpertMark7 = 0.77059314910348709,
                            ExpertMark8 = 0.28130978814735552,
                            ExpertMark9 = 0.079809546550066446,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 33
                        },
                        new
                        {
                            Id = 16,
                            ExpertMark1 = 0.57169664906627826,
                            ExpertMark10 = 0.46638412439274834,
                            ExpertMark2 = 0.051589545548574534,
                            ExpertMark3 = 0.48267869343626368,
                            ExpertMark4 = 0.82930520640125138,
                            ExpertMark5 = 0.34940377007072387,
                            ExpertMark6 = 0.77665688727364179,
                            ExpertMark7 = 0.20068470564630903,
                            ExpertMark8 = 0.5431388716691059,
                            ExpertMark9 = 0.47560513160376316,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 34
                        },
                        new
                        {
                            Id = 17,
                            ExpertMark1 = 0.034782619859019537,
                            ExpertMark10 = 0.097392629264060004,
                            ExpertMark2 = 0.22199634333423868,
                            ExpertMark3 = 0.4071948083784781,
                            ExpertMark4 = 0.13021558805760824,
                            ExpertMark5 = 0.54372538158654393,
                            ExpertMark6 = 0.17324305813884877,
                            ExpertMark7 = 0.7730282766043084,
                            ExpertMark8 = 0.84989296479316923,
                            ExpertMark9 = 0.8715594877402898,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 35
                        },
                        new
                        {
                            Id = 18,
                            ExpertMark1 = 0.024932629205858259,
                            ExpertMark10 = 0.38438830843595961,
                            ExpertMark2 = 0.032661368832503035,
                            ExpertMark3 = 0.81882441963932051,
                            ExpertMark4 = 0.38886369827127532,
                            ExpertMark5 = 0.90135653933840287,
                            ExpertMark6 = 0.6491092446150073,
                            ExpertMark7 = 0.56369617279478212,
                            ExpertMark8 = 0.14956769981222706,
                            ExpertMark9 = 0.85570981282051195,
                            RiskExpertMarksCategoryId = 2,
                            RiskId = 36
                        },
                        new
                        {
                            Id = 19,
                            ExpertMark1 = 0.33074906882408994,
                            ExpertMark10 = 0.68372494805314787,
                            ExpertMark2 = 0.87643498667356967,
                            ExpertMark3 = 0.10475247747477845,
                            ExpertMark4 = 0.19293372285232602,
                            ExpertMark5 = 0.97599446792804845,
                            ExpertMark6 = 0.71718314619181578,
                            ExpertMark7 = 0.28863739724191717,
                            ExpertMark8 = 0.92243400977428602,
                            ExpertMark9 = 0.14726415609593446,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 37
                        },
                        new
                        {
                            Id = 20,
                            ExpertMark1 = 0.6113555222665672,
                            ExpertMark10 = 0.67176676482378517,
                            ExpertMark2 = 0.33863100204531071,
                            ExpertMark3 = 0.42565030318626762,
                            ExpertMark4 = 0.076674802369933182,
                            ExpertMark5 = 0.55530686033048871,
                            ExpertMark6 = 0.81041418331833026,
                            ExpertMark7 = 0.2337523489262473,
                            ExpertMark8 = 0.49487775430842684,
                            ExpertMark9 = 0.40081851453262973,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 38
                        },
                        new
                        {
                            Id = 21,
                            ExpertMark1 = 0.02343247675280169,
                            ExpertMark10 = 0.74428054385920894,
                            ExpertMark2 = 0.21798784556111739,
                            ExpertMark3 = 0.51066825626807244,
                            ExpertMark4 = 0.66039744374326281,
                            ExpertMark5 = 0.93667093550181846,
                            ExpertMark6 = 0.35450487335807934,
                            ExpertMark7 = 0.11344419193704403,
                            ExpertMark8 = 0.32303728008234656,
                            ExpertMark9 = 0.33044795423376705,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 39
                        },
                        new
                        {
                            Id = 22,
                            ExpertMark1 = 0.67896187973349031,
                            ExpertMark10 = 0.74361897576096403,
                            ExpertMark2 = 0.17919253488614062,
                            ExpertMark3 = 0.19642740927137436,
                            ExpertMark4 = 0.16849137354866439,
                            ExpertMark5 = 0.75821983551947081,
                            ExpertMark6 = 0.10417974538311214,
                            ExpertMark7 = 0.80175763887091589,
                            ExpertMark8 = 0.95747135813234119,
                            ExpertMark9 = 0.91953124641732165,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 40
                        },
                        new
                        {
                            Id = 23,
                            ExpertMark1 = 0.85560213160904108,
                            ExpertMark10 = 0.62950885154172609,
                            ExpertMark2 = 0.17577493166577296,
                            ExpertMark3 = 0.27544936476893023,
                            ExpertMark4 = 0.0097301049170681608,
                            ExpertMark5 = 0.78312251552752554,
                            ExpertMark6 = 0.43505185145569214,
                            ExpertMark7 = 0.22169164154148024,
                            ExpertMark8 = 0.40759583091798834,
                            ExpertMark9 = 0.0038574466345708824,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 41
                        },
                        new
                        {
                            Id = 24,
                            ExpertMark1 = 0.90033868627957148,
                            ExpertMark10 = 0.28959213642029502,
                            ExpertMark2 = 0.098526964364932912,
                            ExpertMark3 = 0.7049661157151309,
                            ExpertMark4 = 0.095385001652882107,
                            ExpertMark5 = 0.9227606901798816,
                            ExpertMark6 = 0.16701492550137054,
                            ExpertMark7 = 0.82738348329193234,
                            ExpertMark8 = 0.65402322744017694,
                            ExpertMark9 = 0.52608308150081207,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 42
                        },
                        new
                        {
                            Id = 25,
                            ExpertMark1 = 0.43430647073471784,
                            ExpertMark10 = 0.89078585826929868,
                            ExpertMark2 = 0.54724553606671156,
                            ExpertMark3 = 0.051267795716263498,
                            ExpertMark4 = 0.37229917223380582,
                            ExpertMark5 = 0.86395766593009227,
                            ExpertMark6 = 0.39390074516795714,
                            ExpertMark7 = 0.24725924759918894,
                            ExpertMark8 = 0.53797517639302872,
                            ExpertMark9 = 0.11708171395880151,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 43
                        },
                        new
                        {
                            Id = 26,
                            ExpertMark1 = 0.94967239542942117,
                            ExpertMark10 = 0.37811303347321057,
                            ExpertMark2 = 0.31639056622331874,
                            ExpertMark3 = 0.007230622772705142,
                            ExpertMark4 = 0.13499831740623747,
                            ExpertMark5 = 0.91534058009626762,
                            ExpertMark6 = 0.48436865455736366,
                            ExpertMark7 = 0.17499407969380698,
                            ExpertMark8 = 0.24632209384001569,
                            ExpertMark9 = 0.17450896650599845,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 44
                        },
                        new
                        {
                            Id = 27,
                            ExpertMark1 = 0.9403979174536915,
                            ExpertMark10 = 0.73050553751435243,
                            ExpertMark2 = 0.36737259770047492,
                            ExpertMark3 = 0.99466871238766563,
                            ExpertMark4 = 0.19855825689053197,
                            ExpertMark5 = 0.15822601701443917,
                            ExpertMark6 = 0.94506216879983074,
                            ExpertMark7 = 0.25193949185557363,
                            ExpertMark8 = 0.36865829933610272,
                            ExpertMark9 = 0.67880100164566792,
                            RiskExpertMarksCategoryId = 3,
                            RiskId = 45
                        },
                        new
                        {
                            Id = 28,
                            ExpertMark1 = 0.88659871052615802,
                            ExpertMark10 = 0.5243784386767546,
                            ExpertMark2 = 0.69389499143438027,
                            ExpertMark3 = 0.32885440302568625,
                            ExpertMark4 = 0.19530492175213188,
                            ExpertMark5 = 0.3385091000393694,
                            ExpertMark6 = 0.13604269491026044,
                            ExpertMark7 = 0.13557153152687584,
                            ExpertMark8 = 0.34582474010432773,
                            ExpertMark9 = 0.2551772490949249,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 46
                        },
                        new
                        {
                            Id = 29,
                            ExpertMark1 = 0.25734550009118462,
                            ExpertMark10 = 0.56431237759737396,
                            ExpertMark2 = 0.91872818999959804,
                            ExpertMark3 = 0.89640049735592786,
                            ExpertMark4 = 0.90502405669111718,
                            ExpertMark5 = 0.98354168174924173,
                            ExpertMark6 = 0.59412387136411471,
                            ExpertMark7 = 0.41464963930390597,
                            ExpertMark8 = 0.19288132878856212,
                            ExpertMark9 = 0.86776573615556962,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 47
                        },
                        new
                        {
                            Id = 30,
                            ExpertMark1 = 0.26548672945442164,
                            ExpertMark10 = 0.91860219952983735,
                            ExpertMark2 = 0.3139284861915409,
                            ExpertMark3 = 0.99357158214521812,
                            ExpertMark4 = 0.77594239037093748,
                            ExpertMark5 = 0.50701019338603348,
                            ExpertMark6 = 0.78608870605181591,
                            ExpertMark7 = 0.7629092264862597,
                            ExpertMark8 = 0.47899609092751938,
                            ExpertMark9 = 0.77843430448198769,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 48
                        },
                        new
                        {
                            Id = 31,
                            ExpertMark1 = 0.77880678510365253,
                            ExpertMark10 = 0.38082919044147312,
                            ExpertMark2 = 0.15987115220929449,
                            ExpertMark3 = 0.20195000195851009,
                            ExpertMark4 = 0.59280911665452074,
                            ExpertMark5 = 0.96437711936263848,
                            ExpertMark6 = 0.91708039317820023,
                            ExpertMark7 = 0.68078782319839037,
                            ExpertMark8 = 0.44553416476990748,
                            ExpertMark9 = 0.22405613745771191,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 49
                        },
                        new
                        {
                            Id = 32,
                            ExpertMark1 = 0.68071624015248711,
                            ExpertMark10 = 0.86042724160485484,
                            ExpertMark2 = 0.82862845119808204,
                            ExpertMark3 = 0.77888575710696328,
                            ExpertMark4 = 0.0056764377646427722,
                            ExpertMark5 = 0.5251883072578758,
                            ExpertMark6 = 0.50883171257895232,
                            ExpertMark7 = 0.51287845517202624,
                            ExpertMark8 = 0.43209184217003371,
                            ExpertMark9 = 0.45420225538957315,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 50
                        },
                        new
                        {
                            Id = 33,
                            ExpertMark1 = 0.072919430518489814,
                            ExpertMark10 = 0.56327754666804553,
                            ExpertMark2 = 0.32074073265215752,
                            ExpertMark3 = 0.69291287025170667,
                            ExpertMark4 = 0.035312421239103498,
                            ExpertMark5 = 0.1412998152622571,
                            ExpertMark6 = 0.91161779556554723,
                            ExpertMark7 = 0.40822214601003026,
                            ExpertMark8 = 0.038590239644472057,
                            ExpertMark9 = 0.0085376914795942671,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 51
                        },
                        new
                        {
                            Id = 34,
                            ExpertMark1 = 0.27353351002900073,
                            ExpertMark10 = 0.97023489375497818,
                            ExpertMark2 = 0.19607749129661589,
                            ExpertMark3 = 0.708272622916852,
                            ExpertMark4 = 0.44840746990071845,
                            ExpertMark5 = 0.94863772413209568,
                            ExpertMark6 = 0.98093275397330226,
                            ExpertMark7 = 0.99486981451489898,
                            ExpertMark8 = 0.064426993548740374,
                            ExpertMark9 = 0.70823701516960258,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 52
                        },
                        new
                        {
                            Id = 35,
                            ExpertMark1 = 0.72922603824519439,
                            ExpertMark10 = 0.63566736570011795,
                            ExpertMark2 = 0.72663639620977871,
                            ExpertMark3 = 0.43299898451755037,
                            ExpertMark4 = 0.14005592391230615,
                            ExpertMark5 = 0.00034274016283553088,
                            ExpertMark6 = 0.35040206368839755,
                            ExpertMark7 = 0.40525591878115819,
                            ExpertMark8 = 0.36967316510646087,
                            ExpertMark9 = 0.33189651021402899,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 53
                        },
                        new
                        {
                            Id = 36,
                            ExpertMark1 = 0.56402185260873527,
                            ExpertMark10 = 0.9926598370393287,
                            ExpertMark2 = 0.30066935725611221,
                            ExpertMark3 = 0.23962663408766449,
                            ExpertMark4 = 0.04711849429650472,
                            ExpertMark5 = 0.73772161237142986,
                            ExpertMark6 = 0.28459832043931188,
                            ExpertMark7 = 0.61891884507601702,
                            ExpertMark8 = 0.29768242477245044,
                            ExpertMark9 = 0.14728166382065699,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 54
                        },
                        new
                        {
                            Id = 37,
                            ExpertMark1 = 0.97380261343404328,
                            ExpertMark10 = 0.61911554625835452,
                            ExpertMark2 = 0.21887319605926714,
                            ExpertMark3 = 0.34728500804620244,
                            ExpertMark4 = 0.090308050965371534,
                            ExpertMark5 = 0.23662902296498201,
                            ExpertMark6 = 0.77403334655412825,
                            ExpertMark7 = 0.68331395863587652,
                            ExpertMark8 = 0.27728121917507975,
                            ExpertMark9 = 0.062469247298905128,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 55
                        },
                        new
                        {
                            Id = 38,
                            ExpertMark1 = 0.81583053412237538,
                            ExpertMark10 = 0.90910105366866545,
                            ExpertMark2 = 0.93351799774401378,
                            ExpertMark3 = 0.55410245807486203,
                            ExpertMark4 = 0.082855800308512695,
                            ExpertMark5 = 0.59212609894620583,
                            ExpertMark6 = 0.76830245824066523,
                            ExpertMark7 = 0.33997088803625353,
                            ExpertMark8 = 0.45622362445399145,
                            ExpertMark9 = 0.94086040976194618,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 56
                        },
                        new
                        {
                            Id = 39,
                            ExpertMark1 = 0.84572775585684823,
                            ExpertMark10 = 0.21874912854281192,
                            ExpertMark2 = 0.49928249557804183,
                            ExpertMark3 = 0.07141295955332172,
                            ExpertMark4 = 0.92968565798258884,
                            ExpertMark5 = 0.31497140751754982,
                            ExpertMark6 = 0.92571911733302548,
                            ExpertMark7 = 0.73576943614494938,
                            ExpertMark8 = 0.80480221507281291,
                            ExpertMark9 = 0.19231851140031941,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 57
                        },
                        new
                        {
                            Id = 40,
                            ExpertMark1 = 0.67768207228843402,
                            ExpertMark10 = 0.69246725654545771,
                            ExpertMark2 = 0.42456505050108606,
                            ExpertMark3 = 0.51480572881969122,
                            ExpertMark4 = 0.52700574206019202,
                            ExpertMark5 = 0.43939577659133688,
                            ExpertMark6 = 0.47231565891956395,
                            ExpertMark7 = 0.66492525034061423,
                            ExpertMark8 = 0.11565855527180768,
                            ExpertMark9 = 0.078699389307677503,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 58
                        },
                        new
                        {
                            Id = 41,
                            ExpertMark1 = 0.35556397529232964,
                            ExpertMark10 = 0.8212024766665359,
                            ExpertMark2 = 0.76371134435032328,
                            ExpertMark3 = 0.39775851167162624,
                            ExpertMark4 = 0.52658671920851918,
                            ExpertMark5 = 0.67529084613612766,
                            ExpertMark6 = 0.89661852783051998,
                            ExpertMark7 = 0.49964315385541513,
                            ExpertMark8 = 0.76881950077561323,
                            ExpertMark9 = 0.65065566876016945,
                            RiskExpertMarksCategoryId = 4,
                            RiskId = 59
                        });
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpertCoef1")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef10")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef2")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef3")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef4")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef5")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef6")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef7")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef8")
                        .HasColumnType("int");

                    b.Property<int>("ExpertCoef9")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RiskExpertMarksCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 10,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 8,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 10,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 8,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 10,
                            Name = "Множина настання технічних ризикових подій"
                        },
                        new
                        {
                            Id = 2,
                            ExpertCoef1 = 10,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 7,
                            ExpertCoef4 = 10,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 10,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 7,
                            ExpertCoef9 = 8,
                            Name = "Множина настання вартісних ризикових подій"
                        },
                        new
                        {
                            Id = 3,
                            ExpertCoef1 = 6,
                            ExpertCoef10 = 6,
                            ExpertCoef2 = 10,
                            ExpertCoef3 = 6,
                            ExpertCoef4 = 6,
                            ExpertCoef5 = 7,
                            ExpertCoef6 = 5,
                            ExpertCoef7 = 10,
                            ExpertCoef8 = 6,
                            ExpertCoef9 = 6,
                            Name = "Множина настання планових ризикових подій"
                        },
                        new
                        {
                            Id = 4,
                            ExpertCoef1 = 9,
                            ExpertCoef10 = 8,
                            ExpertCoef2 = 8,
                            ExpertCoef3 = 10,
                            ExpertCoef4 = 8,
                            ExpertCoef5 = 8,
                            ExpertCoef6 = 7,
                            ExpertCoef7 = 7,
                            ExpertCoef8 = 10,
                            ExpertCoef9 = 9,
                            Name = "Множина настання ризикових подій реалізації процесу управління програмним проектом"
                        });
                });

            modelBuilder.Entity("AppRisks.Models.Risk", b =>
                {
                    b.HasOne("AppRisks.Models.RiskCategory", "RiskCategory")
                        .WithMany("Risks")
                        .HasForeignKey("RiskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarks", b =>
                {
                    b.HasOne("AppRisks.Models.RiskExpertMarksCategory", "RiskExpertMarksCategory")
                        .WithMany("RiskExpertMarksList")
                        .HasForeignKey("RiskExpertMarksCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppRisks.Models.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("RiskExpertMarksCategory");
                });

            modelBuilder.Entity("AppRisks.Models.RiskCategory", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("AppRisks.Models.RiskExpertMarksCategory", b =>
                {
                    b.Navigation("RiskExpertMarksList");
                });
#pragma warning restore 612, 618
        }
    }
}
